### ISSUE TITLE
Decide what to do with sourceforge svn checkouts

### ISSUE THREAD

**Issue by jacknagel** [Homebrew/legacy-homebrew#33330]
We're not very consistent in how we handle svn checkouts from sourceforge.

Checking out over HTTPS from sourceforge produces a certification verification error and an interactive prompt like this:

```
Error validating server certificate for 'https://wladx.svn.sourceforge.net:443':
 - The certificate is not issued by a trusted authority. Use the
   fingerprint to validate the certificate manually!
Certificate information:
 - Hostname: *.svn.sourceforge.net
 - Valid: from Thu, 08 May 2014 00:00:00 GMT until Sun, 07 Jun 2015 23:59:59 GMT
 - Issuer: GeoTrust Inc., US
 - Fingerprint: 39:14:cc:ac:41:da:21:19:9a:70:d8:a9:a0:da:62:e9:b1:4a:3f:64
(R)eject, accept (t)emporarily or accept (p)ermanently?
```

So here are some options:
  * Always check out over HTTPS. This is of little value if we cannot trust the certificate, but it may work behind corporate firewalls when regular HTTP does not. The error and prompt can be suppressed using `UnsafeSubversionDownloadStrategy`, but I'd like to eliminate rather than encourage its use.
  * Always check out over regular HTTP. May not work behind firewalls.
  * Always check out over the SVN protocol. Faster than HTTP, but unlikely to work behind firewalls.

Here's a summary of current sourceforge svn checkouts:

#### HTTP
  * netpbm `http://svn.code.sf.net/p/netpbm/code/advanced` (stable)
  * ode: `http://opende.svn.sourceforge.net/svnroot/opende/trunk` (head)
  * spim:  `http://svn.code.sf.net/p/spimsimulator/code` (stable)
  * vgmstream: `http://svn.code.sf.net/p/vgmstream/code` (stable)
  * xmlrpc-c: `http://svn.code.sf.net/p/xmlrpc-c/code/stable` (stable)
  * sdcv `http://svn.code.sf.net/p/sdcv/code/trunk` (stable)

#### HTTPS
  * ctags: `https://svn.code.sf.net/p/ctags/code/trunk` (head)
  * <strike>doxygen: `https://doxygen.svn.sourceforge.net/svnroot/doxygen/trunk` (head)</strike> switched to git
  * gmtl: `https://ggt.svn.sourceforge.net/svnroot/ggt/trunk` (head)
  * gpac: `https://gpac.svn.sourceforge.net/svnroot/gpac/trunk/gpac` (head)
  * irrlicht: `https://irrlicht.svn.sourceforge.net/svnroot/irrlicht/trunk` (head)
  * lasi: `https://lasi.svn.sourceforge.net/svnroot/lasi/trunk` (head)
  * nzbget: `https://nzbget.svn.sourceforge.net/svnroot/nzbget/trunk` (head)
  * sdcc: `https://sdcc.svn.sourceforge.net/svnroot/sdcc/trunk/sdcc` (head)
  * teem: `https://teem.svn.sourceforge.net/svnroot/teem/teem/trunk` (head)
  * unfs3: `https://svn.code.sf.net/p/unfs3/code/trunk` (head)
  * wla-dx: `https://wladx.svn.sourceforge.net/svnroot/wladx` (head)

#### SVN protocol
  * dasm: `svn://svn.code.sf.net/p/dasm-dillon/code/trunk` (head)
  * gpsim: `svn://svn.code.sf.net/p/gpsim/code/trunk` (head)
  * rcslogplayer: `svn://svn.code.sf.net/p/sserver/code/rcss/trunk/rcsslogplayer` (head + resources)

**Comment by apjanke** [comment]
Hi folks.

I think the issue here is that a) the system `svn` is using the system OpenSSL library, and b) the system OpenSSL library ships without a list of trusted root certificates. (Why? I dunno.) The HTTPS downloads with the system `svn` could be fixed by making it aware of the root certificates.

The Homebrew `openssl` formula [bootstraps a cert.pem file from the system keychains](https://github.com/Homebrew/homebrew/blob/b35c6403392e2829291ef0833b05fd25e588992e/Library/Formula/openssl.rb#L104-L122). With that file in existence, I was able to get the system `svn` on 10.9.5 to work using the `SSL_CERT_FILE` openssl configuration variable.

```
➜  svn  /usr/bin/svn checkout https://svn.code.sf.net/p/ctags/code/trunk work/foo
Error validating server certificate for 'https://svn.code.sf.net:443':
 - The certificate is not issued by a trusted authority. Use the
   fingerprint to validate the certificate manually!
Certificate information:
 - Hostname: *.code.sf.net
 - Valid: from Thu, 16 Apr 2015 00:00:00 GMT until Sun, 15 May 2016 23:59:59 GMT
 - Issuer: GeoTrust Inc., US
 - Fingerprint: 1f:7b:73:d5:cf:71:18:76:d5:23:f3:07:c9:2f:f5:4a:52:67:0f:68
(R)eject, accept (t)emporarily or accept (p)ermanently? r
svn: E175002: Unable to connect to a repository at URL 'https://svn.code.sf.net/p/ctags/code/trunk'
svn: E175002: OPTIONS of 'https://svn.code.sf.net/p/ctags/code/trunk': Server certificate verification failed: issuer is not trusted (https://svn.code.sf.net)
➜  svn  SSL_CERT_FILE=/usr/local/etc/openssl/cert.pem /usr/bin/svn checkout https://svn.code.sf.net/p/ctags/code/trunk work/foo
A    work/foo/sql.c
A    work/foo/tex.c
A    work/foo/options.h
A    work/foo/args.h
A    work/foo/Makefile.in
A    work/foo/entry.c
```

This lets you use HTTPS securely (still validating the server certificate), consistent with the system's own trust policy.

Maybe you could have a build-time dependency on Homebrew's `openssl` just to get that `certs.pem` file to point to, even if you're using the system `svn`. Or make a special formula that just bootstraps a `certs.pem` file from the system keychain using the system OpenSSL.

**Comment by MikeMcQuaid** [comment]
We'll accept PRs for this but we're not actively working on it at this time.
