### ISSUE TITLE
Shall we run `brew update` automatically?

### ISSUE THREAD

**Issue by MikeMcQuaid** [Homebrew/legacy-homebrew#38818]
This would fix a lot of issues people have. Obviously we'd need to catch/handle the "no internet connection" case but otherwise it seems sensible to me.

**Comment by xu-cheng** [comment]
By `automatically`, you mean run it before `brew install` etc, or as a separate service?

I'm kinda :-1: for running `brew update` automatically before every brew commands. Maybe it's because I don't have decent network, it took 10~20 secs to finish `brew update`.

If it's a service, there is a PR(#37943) by @DomT4.

**Comment by mikemcquaid** [comment]
Before `brew install` if it's not been e.g. updated for 24 hours. The "self-update before run" pattern is relatively common in other software and it will fix the almost daily issues we see where people haven't got a fixed version of software yet.

**Comment by DomT4** [comment]
I agree with Xu that the network lag is going to be a problem, or at least will confuse people at first, but I agree with Mike that it needs to be done regardless.

Not updating prior to installing things is one of the biggest causes of issues Homebrew sees. Since we're not doing an ` upgrade ` afterwards by default, the change would be pretty non-invasive.

**Comment by tdsmith** [comment]
I like the idea but I think this could make working on formulas locally kind of annoying; I feel like I'll have to cancel out of vim merge-commit-message sessions and `!! --dont-do-that` a lot. If we're auto-stashing changes on update now it'll be worse.

We could print a message (that users will ignore)?

**Comment by bcomnes** [comment]
I auto-update if its been more than 24 hours via ansible and it works out great.  The only possible issue is that if people get sloppy and make local formula edits without properly committing or stashing them.  What if this is the default for new installs, and existing installs remain opt in?

**Comment by chdiza** [comment]
This seems OK as long as three things are the case:

(1) That there is some kind of explicit opt-outability, like `brew install --no-update-first`, or a shell var;

(2) That this doesn't affect the brewing of local, custom formulas;

(3) That a `brew install` will NOT automatically fail if one's internet connection is down, or purposely turned off.  One should be able to brew on a plane or a bus or during a power outage, etc, because of (a) the cache and (b) custom formulas can point to locally-stored tarballs.

I note that (2) could automatically be covered by satisfying (1).  And that (3) is currently satisfied except for the case of brewing from HEAD (which I think is a bug, but that's for a later time).

**Comment by mikemcquaid** [comment]
I'd probably disable this behaviour if HOMEBREW_DEVELOPER is set or when using a flag.

> (3) That a brew install will NOT automatically fail if one's internet connection is down, or purposely turned off. One should be able to brew on a plane or a bus or during a power outage, etc, because of (a) the cache and (b) custom formulas can point to locally-stored tarballs.

I completely agree here; I do a lot of work on trains/planes so this is very important to me. I'd see this as checking if the internet connection is up before doing anything (probably seeing if a single ping to github.com responds within a second).

**Comment by chdiza** [comment]
>  I'd see this as checking if the internet connection is up before doing anything (probably seeing if a single ping to github.com responds within a second).

One could also, before that, test that wifi is even ON.  Using, perhaps `networksetup -getairportpower -en1`, or by querying (and grepping) `/System/Library/PrivateFrameworks/Apple80211.framework/Resources/airport`, or some better method.

This will save the one second waiting for a ping.

**Comment by DomT4** [comment]
Testing wifi may not be enough. I don't think that'll cover USB and/or bluetooth tethering, which doesn't require the wifi antenna to be active.

**Comment by chdiza** [comment]
@DomT4 Totally right; Wifi was the only thing I could remember how to do off the top of my head.

What about (for wifi and ethernet, anyway):
```
ipconfig 2>/dev/null getifaddr en1
ipconfig 2>/dev/null getifaddr en0
```
AFAIK, the top one will have empty output iff [ either wifi is off or wifi is on but unconnected ], and, the bottom one will have empty output iff [ either ethernet is unplugged or it's plugged in but not connected to a network ].

**Comment by DomT4** [comment]
Aye, makes sense to me. I favour @chdiza's method for Wi-Fi and Ethernet, and if we detect neither of those active, we can fallback on sending out the ping. Should cover all possible bases effectively.

**Comment by chdiza** [comment]
> if we detect neither of those active, we can fallback on sending out the ping

Wait, I'm confused.  Don't you mean that if neither of those are active we forget about pinging?  Why send a ping if there's no internet connection?  And if that's not what you meant, then what's the point of doing the check?

**Comment by DomT4** [comment]
Sorry - I meant if we don't detect wifi or ethernet active, we could throw a ping to account for the possibility of USB/Bluetooth tethering being active - The latter being harder to get ` ipconfig ` or ` networksetup ` to cough up detail about.

**Comment by chdiza** [comment]
> we could throw a ping to account for the possibility of USB/Bluetooth tethering being active

I confused myself wrt my own suggestion earlier.

Main purpose: (a) do not sit through a pointless ping round-trip if internet is on, and (b) don't sit around waiting for ping to timeout if internet is off.

I'm not handy with pinging; Does ping error out *instantly* when the internet is down?  If so, then (b) is taken care of automatically.

**Comment by DomT4** [comment]
> Does ping error out instantly when the internet is down?

No, but we can make it give up after a second. ` ping -t 1 somewebsite.com `.

**Comment by chdiza** [comment]
> No, but we can make it give up after a second.

I really don't want to sit around and wait for a doomed ping :)

That's half the reason for my ipconfig/networksetup brainstorming.  (The other half being: I don't want to sit around and wait for a non-doomed ping either.)

I did a little experimenting, and I found that with my internet shut off, `ping somewebsite.com` will error out instantly (at least on 10.10.3): `ping: cannot resolve XXX: unknown host`.  Couldn't that be caught and used as a sign that the internet is off?

If so, first do the ipconfig or whatever is settled on.  If it yields an IP address the internet is on, so skip the ping and go straight to `brew update`.  If it yields empty output, attempt to ping.  If the internet is off, ping will fail instantly and we skip `update`.  If the ping returns, then the user has a strange connection that nevertheless works, and we go straight to `update`.  This way, the only people who have to sit through a ping are the 1% who have an internet connection that runs neither through wifi nor ethernet.

**Comment by DomT4** [comment]
> I did a little experimenting, and I found that with my internet shut off

Neat. I thought ` ping ` just carried on forever without a timeout stated or someone manually cancelling it. Maybe that's just if there's a connection though; I haven't tried to ` ping ` without a connection for a while :smile_cat:.

Yeah, should be possible to intercept the output and prevent the whole ` brew install ` falling apart because it can't ` update ` at that moment.

**Comment by mikemcquaid** [comment]
Just to chip in and say: don't worry, I'll try various (quick) approaches. Worst case this will take 2-3 seconds and most likely case will be <1 second.

**Comment by geoff-codes** [comment]
You could compare the a checksum of a formula foo.rb  against `curl -Lsm1 https://raw.github.com/Homebrew/homebrew/master/Library/Formula/foo.rb`. If they match, no need; if they don't match, pull. If curl times out, maybe issue a warning?

**Comment by evotopid** [comment]
In general I think it's a good thing to add this functionality but really only if it is optional. I would even wonder if it is what should be the default, as maybe the updating before every install would be annoying to some. At least I don't like software that does many of these auto updates etc. without really informing me, it would have to be printed clearly on the terminal that homebrew is performing an automatic update.
However I think the way to go would be displaying a message when the database is old (preferably in red or orange) noting how long ago the last update was and that the user can perform an update of the formulas and also how auto updating can be enabled if wished. I think that would be the least intrusive way of achieving this, but feel free to correct me if you think that I'm wrong.

Also @geoff-codes: The issue with checksums would probably be, that if a formula is updated it's also possible that its dependencies have also changed and that in the end many requests would have to be made to achieve the same what the normal update mechanism would do.

**Comment by mikemcquaid** [comment]
Let's hold off further discussion here folks, I think we've got enough to work from here. To be diplomatic: if you're commenting on the Homebrew issue tracker about your thoughts on this then you aren't the target user whose problems this would be addressing.

**Comment by geoff-codes** [comment]
Heh. Good point.

**Comment by darrynten** [comment]
I can see this being a useful option. Any chance that this can be made as an optional configuration variable?

**Comment by mikemcquaid** [comment]
@darrynten I might do that.

**Comment by apjanke** [comment]
When you do a ‘ping <name>‘, it has to do a DNS resolution first, before sending out the ICMP ping packet. That's the "unknown host" error. The DNS resolution can fail near-instantly regardless of ping timeout. On the other hand, it can also succeed even if you're offline, if that particular hostname has been cached or has a local definition.

It's possible to get fast-fail NAK replies to actual pings, too, but not common. More common is false-negative timeouts due to providers filtering out ICMP. I'd make a trivial regular TCP request if you want a real liveness check.

Sorry for responding to a stale issue.

IMHO the simpler option of a "your definitions are old; you should update" warning is a good idea and worth pursuing even if you don't want to tackle the auto-updating and network detection stuff.

**Comment by DomT4** [comment]
@mikemcquaid Is this still live?

**Comment by mikemcquaid** [comment]
@DomT4 Somewhat but I think it's blocked on a few things:

- Making `brew update` use a Bash wrapper so that the Ruby code is always up-to-date by the time any of it is loaded.
- Making `brew update` far, far faster in the case that there are no upstream changes
- Possibly parallelising `brew update` fetches (this is relatively easy with Bash as we can fork all these processes and wait for them to all finish).

**Comment by geoff-codes** [comment]
@mikemcquaid I was kinda bored.

```sh
#!/bin/sh # brew-update.sh
[ -n "$HOMEBREW_VERBOSE" ] && set -x

update_if_necessary()
( # function()( ... ) = explicit subshell
  cd "$@"   
  ref=$(git symbolic-ref HEAD)
  remote_sha=$(git ls-remote --heads -q | grep $ref | cut -c1-40)
  local_sha=$(git rev-parse HEAD -q)
  
  [ "$remote_sha" != "$local_sha" ] &&
    {
      { git stash save --include-untracked >/dev/null 2>&1 || :;} &&
      { pwd -P && git pull --ff --no-rebase ;}                    &&
      { git stash pop >/dev/null 2>&1 || :;}
    }
)

brewprefix=$(brew --prefix)

for each in $brewprefix $(ls -1d $brewprefix/Library/Taps/*/* 2>/dev/null); do
  update_if_necessary "$each" &
done
wait

```

---

With 7 taps:
```sh
> time brew update.sh
real 0m2.012s
user 0m0.662s
sys  0m0.301s

```

```sh
> time brew update
real 0m9.925s
user 0m0.647s
sys  0m0.519s
```

**Comment by mikemcquaid** [comment]
Nice approach but I suspect that's mostly down to the parallelisation of the network calls rather than the `ls-remote`. It might be interesting to see if using GitHub's API is faster still.

**Comment by geoff-codes** [comment]
Actually, the Refs API is what I tried first. They're basically identical, speed wise:
```sh
#!/bin/bash # test github refs api vs git ls-remote --heads for speed

cd $(brew --prefix)

echo git refs api:

# (Becomes https://api.github.com/repos/Homebrew/homebrew/git/refs/heads/master with a standard configuration.)

for x in $(seq 1 10); do
 time curl -Ls $(git ls-remote --get-url | sed \
 -e's|github\.com|api.github.com/repos|' -e's|\.git$||' \
 -e's|$|/git/|')$(git symbolic-ref HEAD) | grep sha | sed 's|.* "\(.*\)",|\1|'
done

echo git ls-remote:

for y in $(seq 1 10); do
  time git ls-remote --heads -q | grep $(git symbolic-ref HEAD) | cut -c1-40
done
```
Produces:
```
git refs api:

6d2714f1e69545f822d89b05673f04fc77ae2dde

real	0m1.723s
user	0m0.030s
sys	0m0.015s
6d2714f1e69545f822d89b05673f04fc77ae2dde

real	0m1.791s
user	0m0.032s
sys	0m0.018s
6d2714f1e69545f822d89b05673f04fc77ae2dde

real	0m1.536s
user	0m0.032s
sys	0m0.018s
6d2714f1e69545f822d89b05673f04fc77ae2dde

real	0m1.534s
user	0m0.032s
sys	0m0.017s
6d2714f1e69545f822d89b05673f04fc77ae2dde

real	0m1.395s
user	0m0.031s
sys	0m0.016s
6d2714f1e69545f822d89b05673f04fc77ae2dde

real	0m1.375s
user	0m0.033s
sys	0m0.018s
6d2714f1e69545f822d89b05673f04fc77ae2dde

real	0m1.842s
user	0m0.034s
sys	0m0.017s
6d2714f1e69545f822d89b05673f04fc77ae2dde

real	0m1.615s
user	0m0.032s
sys	0m0.017s
6d2714f1e69545f822d89b05673f04fc77ae2dde

real	0m1.978s
user	0m0.032s
sys	0m0.018s
6d2714f1e69545f822d89b05673f04fc77ae2dde

real	0m2.548s
user	0m0.032s
sys	0m0.018s
```
```
git ls-remote:

6d2714f1e69545f822d89b05673f04fc77ae2dde

real	0m1.791s
user	0m0.101s
sys	0m0.080s
6d2714f1e69545f822d89b05673f04fc77ae2dde

real	0m1.864s
user	0m0.092s
sys	0m0.073s
6d2714f1e69545f822d89b05673f04fc77ae2dde

real	0m1.652s
user	0m0.100s
sys	0m0.077s
6d2714f1e69545f822d89b05673f04fc77ae2dde

real	0m1.647s
user	0m0.097s
sys	0m0.071s
6d2714f1e69545f822d89b05673f04fc77ae2dde

real	0m1.767s
user	0m0.098s
sys	0m0.078s
6d2714f1e69545f822d89b05673f04fc77ae2dde

real	0m1.747s
user	0m0.093s
sys	0m0.071s
6d2714f1e69545f822d89b05673f04fc77ae2dde

real	0m1.639s
user	0m0.093s
sys	0m0.072s
6d2714f1e69545f822d89b05673f04fc77ae2dde

real	0m1.706s
user	0m0.089s
sys	0m0.055s
6d2714f1e69545f822d89b05673f04fc77ae2dde

real	0m1.681s
user	0m0.096s
sys	0m0.076s
6d2714f1e69545f822d89b05673f04fc77ae2dde

real	0m1.660s
user	0m0.090s
sys	0m0.063s
```
Its nothing more that pure latency, I think. Maybe you can see how the two fare speed-wise across the pond?

But in any case the **real** reason I dropped using the API is that the rate-limit on the Refs API is ridiculously low. I got locked out before I even finished writing the script. While authenticating would resolve that of corse, the whole idea here being "Shall we run `brew update` automatically?", there'd probably be a lot of users who haven't taken the time to set a HOMEBREW_GITHUB_API_TOKEN who would run into trouble.

**Comment by mikemcquaid** [comment]
I see a real difference in speed between the two:

```shell
$ /usr/bin/time git ls-remote --heads https://github.com/Homebrew/homebrew
6d2714f1e69545f822d89b05673f04fc77ae2dde	refs/heads/master
        3.80 real         0.25 user         0.13 sys

$ /usr/bin/time curl --silent -o /dev/null https://api.github.com/repos/Homebrew/homebrew
        1.18 real         0.02 user         0.01 sys
```

Additionally, if you specify the ETag (and we cached it locally) it doesn't increase your rate limit either:
```shell
$ /usr/bin/time curl https://api.github.com/repos/Homebrew/homebrew --header 'If-None-Match: "9e6b5713490e7bae62d56a8a971e2770"'
        0.65 real         0.02 user         0.00 sys
```

**Comment by geoff-codes** [comment]
Good call on using the ETag header.

```sh
#!/bin/sh # brew-update.sh
[ -n "$HOMEBREW_VERBOSE" ] && set -x

update_if_necessary()
(
  cd "$@" 

  # Build the URI for the API call based on our remote and branch.
  uri=$(git ls-remote --get-url | sed -e's|git://|https://|' -e's|\.git$||' \
                                      -e's|github.com|api.github.com/repos|')
  ref=$(git symbolic-ref HEAD)
  api_uri=$(echo $uri | sed 's|$|/git|')/$ref
 
  # We save a few milliseconds with a standard config avoiding the refs API.
  [ "$ref" = "refs/heads/master" ] && api_uri="$uri/commits/master"

  etag=$(git config brew.etag) # ETag gets cached in .git/config.
  [ -z "$etag" ] && etag=xxx # On first run, set a fake ETag (for grep).

  response=$(curl -isLH "If-None-Match: \"$etag\"" $api_uri)

  # If the ETag matches, we can exit now.
  echo "$response" | grep "ETag: \"$etag\"" >/dev/null 2>&1 && return 0 ||
  {
    { git stash save --include-untracked >/dev/null 2>&1 || :;} &&
    { git pull --ff --no-rebase ;}                              &&
    { git stash pop >/dev/null 2>&1 || :;}

    # Cache the new ETag in the .git/config
    etag=$(echo "$response" | grep 'ETag:' | sed 's|.* "\(.*\)"|\1|')
    git config brew.etag $(echo $etag | tr -d '\r')
  }
)

brewprefix=$(brew --prefix)

for each in $brewprefix $(ls -1d $brewprefix/Library/Taps/*/* 2>/dev/null); do
  update_if_necessary "$each" &
done
wait

```

After the first run (if we're up to date):

```
> time brew update.sh
real	0m0.858s
user	0m0.583s
sys	0m0.293s
```

Let me know if you want to workshop this in a PR?

**Comment by xu-cheng** [comment]
@geoff-codes Good script. If we can solve following problems, it would be perfect.

* Etags approach only works for Github public repos. But we do support any-tap, i.e.,  private repos or repos from other places. So we need to fallback to normal git operation in such situation.
* Prior to `git pull`, it would be nice to handle branch like what we do now.
* We need handle interrupt. If users send `Ctrl-C`, there shouldn't be nasty output. And things like `git stash` and branch should be restored.

> Let me know if you want to workshop this in a PR?

If it's OK to you, I intent to merge your script into my PR I current worked on, to add support on report, migration etc.

**Comment by geoff-codes** [comment]
@xu-cheng 

> Etags approach only works for Github public repos. But we do support any-tap, i.e., private repos or repos from other places. So we need to fallback to normal git operation in such situation.

I think a combination of both my original `git ls-remote --heads` approach and the ETags approach would probably work for this, since  `git ls-remote --heads` is protocol-agnostic. One could grep the output of the API approach for a 404, then fall back.

> We need handle interrupt. ...

Something like this should do it.

```sh
trap_cleanup()
{
  for job in $(jobs -p); do
    kill -s 2 $job
  done

  for each in $brewprefix $(ls -1d $brewprefix/Library/Taps/*/* 2>/dev/null); do
    cd "$each"
    git config --remove-section brew >/dev/null 2>&1
    git stash pop >/dev/null 2>&1
  done
}

trap trap_cleanup HUP INT QUIT ABRT KILL TERM
```

> Prior to git pull, it would be nice to handle branch like what we do now.

I'm not sure what you mean by this. Could you be more specific? (I actually think there's quite a bit of cruft in the current `update` that slows it down, e.g., `git status --untracked-files=all --porcelain` is pretty unnecessary).

> If it's OK to you, I intent to merge your script into my PR I current worked on, to add support on report, migration etc.

Do you mean there's a topic branch somewhere that you'll add this to? Or is it an open PR? My only reservation is that I'd like to continue to be able to help contributing to this. But ultimately however you and the other @owners want to handle it is fine by me.

:beers:

**Comment by geoff-codes** [comment]
Also, a couple other outstanding issues you reminded me of:
- Need to handle converting SSH URIs to https for the API (or just fall back with these, since it's likely private)
- Because its still possible to hit the API rate limit, it might be nice to add an additional parameter to the config (maybe epoch timestamp), and limit automatic updating to something like once per minute.
- Its worth seriously considering putting this in `brew` (the shell script), since that's more or less the only way to ensure as @mikemcquaid [specified above](https://github.com/Homebrew/homebrew/issues/38818#issuecomment-162446368),

> Making brew update use a Bash wrapper **so that the Ruby code is always up-to-date by the time any of it is loaded.**

**Comment by xu-cheng** [comment]
> I'm not sure what you mean by this. Could you be more specific?

I mean to checkout the upstream branch and restore it after update. [like this.]( https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/cmd/update.rb#L246-L248)

> I actually think there's quite a bit of cruft in the current update that slows it down, e.g., git status --untracked-files=all --porcelain is pretty unnecessary

Can we mitigate this by stashing unconditionally?

> Do you mean there's a topic branch somewhere that you'll add this to? Or is it an open PR? 

I have a working branch on my Mac locally to handle pre-pull and post-pull codes. But my bash is out of practice and I was thinking to use ruby anyway. Glad you help me to sort this out.

> Need to handle converting SSH URIs to https for the API (or just fall back with these, since it's likely private)
Because its still possible to hit the API rate limit, it might be nice to add an additional parameter to the config (maybe epoch timestamp), and limit automatic updating to something like once per minute.

This makes me prefer the pure `git ls-remote --heads` approach  to reduce code complexity(and hence increasing robustness).

> since that's more or less the only way to ensure as @mikemcquaid specified above,

To ensure this, we only need to make update script to create a new brew instance for post-pull matters. Bash is not necessary, but it's more preferred than ruby script due to other reasons. e.g. moving to ruby 2.0 for old OS.

**Comment by mikemcquaid** [comment]
> Need to handle converting SSH URIs to https for the API (or just fall back with these, since they're likely to be private)

Yeh, I think we can punt on this and just assume they are private (at least for a first version).

> Because its still possible to hit the API rate limit, it might be nice to add an additional parameter to the config (maybe an epoch timestamp), and limit automatic updating to something like once per minute.

Yeh. I see automatic updating as being something we can/would tackle later when `brew update` with no changes is much, much faster than it is today. I do think checking the API less depending on the last check and respecting the rate limit is essential. I also think https://github.com/Homebrew/homebrew/issues/46578 may be a (fairly easy) big win here.

> Its worth seriously considering putting this in brew (the shell script), since that's more or less the only way to ensure as @mikemcquaid specified above,

I think having a separate script file would be good but I agree it should be called before we get to the Ruby for speed.

> Can we mitigate this by stashing unconditionally?

We do this as-of https://github.com/Homebrew/homebrew/pull/45825.

> This makes me prefer the pure git ls-remote --heads approach to reduce code complexity(and hence increasing robustness).

It is much slower, though. `brew update` is the slowest Homebrew command that people rerun regularly and I think even getting it down from e.g. 3s to 0.5s would make a big difference to how we can use it.

> To ensure this, we only need to make update script to create a new brew instance for post-pull matters. Bash is not necessary, but it's more preferred than ruby script due to other reasons. e.g. moving to ruby 2.0 for old OS.

I think the least error-prone and speedy way of doing this is ensuring that we don't load any Ruby code until we've updated. Loading our Ruby code and any `brew.rb` invocations is also slow so it would be nice if we can potentially move other things than some of `update` into Bash scripts (e.g. `--version` or `--prefix` are other things that could benefit from being very fast).

**Comment by geoff-codes** [comment]
>> I'm not sure what you mean by this. Could you be more specific?

> I mean to checkout the upstream branch and restore it after update. [like this.](https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/cmd/update.rb#L246-L248)

Yeah, though there's a pretty big edge case that's not handled there.
@mikemcquaid, I think this may have been introduced with #45825?
- Say I'm preparing a PR or two. I make a commit, but I haven't yet renamed the branch or changed upstream tracking. I then check out a new branch from origin/master for the second PR. If I `brew update`, my first commit in the local `master` is wiped out.
I'd much rather do something like a `git fetch --all`, and then maybe try to automatically `git pull --rebase` in `master`, which should work 99% of the time, since y'all adhere to the the GitHub flow so well. Or maybe something like `git branch -m  master master.backup` (if it has a local commit), before doing this. Thoughts?

>> Can we mitigate this by stashing unconditionally?

> We do this as-of #45825.

Yeah, this is also what's being done in the script above with

```sh
{ git stash save --include-untracked >/dev/null 2>&1 || :;}
{ git stash pop >/dev/null 2>&1 || :;}
```
The brackets are for grouping the exit status;  `|| :`  "or [null op]", so it always returns 0.

> I think having a separate script file would be good but I agree it should be called before we get to the Ruby for speed.
Separate script it is. ~~Where would it live? `Library/Homebrew/cmd`? Directly in `bin`? Or?

> I also think #46578 may be a (fairly easy) big win here.
Totally. Though the devil's in the details. I'll give my $0.02 on that over in there.

> It is much slower, though. brew update is the slowest Homebrew command that people rerun regularly and I think even getting it down from e.g. 3s to 0.5s would make a big difference to how we can use it.

Yeah, I think we can probably hit 0.5s if we separate out updating homebrew proper from updating the taps (that is, exec to ruby after finishing updating homebrew, let the taps finish updating in the background).

> Loading our Ruby code and any brew.rb invocations is also slow so it would be nice if we can potentially move other things than some of update into Bash scripts (e.g. --version or --prefix are other things that could benefit from being very fast).

I can definitely help with that! I actually have a few `brew-something`s already in ~~bash~~ POSIX sh, which I wrote a couple years back for various reasons (wonkiness, speed, or missing functionality). [Like this one](https://gist.github.com/geoff-codes/9429311), which I might have even submitted as a PR at one point, I think.

@xu-cheng
I think at this point what I'm gonna do is create a topic branch and a PR for this stuff, since continuing to drop code inline this this issue isn't to anyone's advantage. You could then pull it into your local repo by `ref/pull/#/head`, and we can figure out the if/how/when of merging down the road? If that's ok with you.

**Comment by geoff-codes** [comment]
Or, I could start a tap, like @telemachus did with brew-desc? But there'd still need to be some code tweaked in homebrew, to allow overriding the existing ones...

**Comment by geoff-codes** [comment]
Yikes, some of update.rb is a little rough around the edges.
[You Keep Using This Code](https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/cmd/update.rb#L211), [I Do Not Think It Does What You Think It Does](http://stackoverflow.com/a/8841024/2351351).
:sweat_smile:

**Comment by xu-cheng** [comment]
To give a sense on what's in my mind. You can refer [this](https://github.com/xu-cheng/homebrew/commit/85f0c7d6253de2b1d5cce8566cec1ad35a926df8) to get hand on my planned structure. For `brew update`, there are 3 files involved:

* `cmd/update.rb`: the starting point, it will be responsible to do pre-update checking, set environment etc. It also will maintain a update lock to prevent multiple `brew update` instance.
* `update/update.sh`: This is where you script should lay in. I'm also thinking update script should store initial and end commit in `git config` for latter report.
* `update/post_update.rb`: This will be called in the end of `update/update.sh`. It will load the homebrew code to generate report and possible migrate taps and formulae.

**Comment by geoff-codes** [comment]
@xu-cheng Awesome, I'll take a look very soon; its nearly 4 AM where I am. :sleepy: 

One note: I don't forsee the need for a some sort of mutex; between [git](http://stackoverflow.com/questions/13459219/is-it-safe-if-more-git-commands-are-run-on-the-same-repo-in-parallel) and the the time-based lock/rate limiter, it would be overkill.

We're going to have to clarify what we meant by "brew update [should] use a Bash wrapper so that the Ruby code is always up-to-date by the time any of it is loaded"; your outline would seem violate that precept to me; and it seems somewhat risky, considering we may have different/updated ruby code being loaded while the command is in progress. I was imagining more of an `exec` rather than `popen3` situation.

**Comment by xu-cheng** [comment]
> One note: I don't forsee the need for some sort of mutex; between git and the the time-based lock/rate limiter, it would be overkill.

Mutex is mainly used to help post update report and migrations not git operations.

>  your outline would seem violate that precept to me; and it seems somewhat risky, considering we may have different/updated ruby code being loaded while the command is in progress. 

What we want to achieve is only pre-update or post-update ruby codes are loaded in an instance. So there won't be a mixture of ruby codes in different versions. In my outline, `update.rb` will only load pre-update codes while `post_update.rb` will only load post-update codes. Therefore, it's save to do so.

**Comment by mikemcquaid** [comment]
> Say I'm preparing a PR or two. I make a commit, but I haven't yet renamed the branch or changed upstream tracking. I then check out a new branch from origin/master for the second PR. If I brew update, my first commit in the local master is wiped out. I'd much rather do something like a git fetch --all, and then maybe try to automatically git pull --rebase in master. Which should work 99% of the time, since y'all adhere to the the GitHub flow so well. Or maybe something like git branch -m master master.backup (if it has a local commit) before doing this. Thoughts?

That's a known edge case but anyone familiar with `git` (e.g. `git reflog`) will be able to sort that out. The priority here is non-technical users who don't know or interact with Git.

**Comment by mikemcquaid** [comment]
> cmd/update.rb: the starting point, it will be responsible to do pre-update checking, set environment etc. It also will maintain a update lock to prevent multiple brew update instances.

I'd really like if we can have no Ruby code executed before the update.

> update/update.sh: This is where you script should lay in. I'm also thinking update script should store initial and end commit in git config for later report.
> update/post_update.rb: This will be called in the end of update/update.sh. It will load the homebrew code to generate report and possible migrate taps and formulae.

This means there will need to be two (or more) invocations of `brew.rb` which has a non-trivial overhead.

**Comment by mikemcquaid** [comment]
Also: while we're doing a big refactoring here: we should move away from using `git pull` and instead move to `git fetch && git merge` (or `git fetch && git rebase` for `git pull --rebase`). This gives us more control and means even if the update fails for whatever reason they are still able to have the latest code there.

> What we want to achieve is only pre-update or post-update ruby codes are loaded in an instance. So there won't be a mixture of ruby codes in different versions. In my outline, update.rb will only load pre-update codes while post_update.rb will only load post-update codes. Therefore, it's save to do so.

I think it's perfectly possible to do without the pre-update Ruby code, here. It'll require writing a bit more Bash but that's no bad thing for both speed and avoiding Ruby errors.

**Comment by xu-cheng** [comment]
> I'd really like if we can have no Ruby code executed before the update.

That's little paranoid and impossible. We at least need Ruby code to do minimal doctor check and git existence checking (maybe install git for non-Xcode/CLT installation). And I see little harm to execute Ruby code here, since you will always execute `brew.rb` at first place. Also I don't like to repeat code in Bash and Ruby when can be avoided.

> This means there will need to be two (or more) invocations of brew.rb which has a non-trivial overhead.

Both of these two scripts are standalone. i.e. none of them will invoke brew.rb. The overhead is already at minimum.

**Comment by mikemcquaid** [comment]
> That's little paranoid and impossible.

It's not impossible. If you want to abandon this project and have me show you it's possible: that's fine. I also don't appreciate being called paranoid; I really don't want to pull rank here but I have been working on Homebrew for longer and have more contributions than any other current maintainer: if I'm concerned about something I probably have a half-decent reason.

> We at least need Ruby code to do minimal doctor check and git existence checking (maybe install git for non-Xcode/CLT installation). And I see little harm to execute Ruby code here, since you will always execute brew.rb at first place. Also I don't like to repeat code in Bash and Ruby when can be avoided.

We don't need Ruby code for any of that. If you'd like to avoid repeating code: we can call Bash code from Ruby.

> Both of these two scripts are standalone. i.e. none of them will invoke brew.rb.

Are you going to load e.g. `global.rb`? If not: I don't really see any difference between it being a `brew.rb` invocation or a standalone script. I actually think it's more confusing if we have some standalone Ruby scripts that don't get executed through `brew.rb`.

> The overhead is already at minimum.

That's not the case, even when starting a new Bash process from ZSH:

```bash
$ /usr/bin/time ruby -e "puts 'fish'"
fish
        0.08 real         0.04 user         0.03 sys
$ /usr/bin/time bash -c "echo 'fish'"
fish
        0.00 real         0.00 user         0.00 sys
```

I'm happy to either take over here or leave further discussion of the approach until there's a PR but I feel strongly about us at least trying to do this entirely in Bash and to open the door for other Bash commands that we may want for speed.

**Comment by xu-cheng** [comment]
>  I also don't appreciate being called paranoid; I really don't want to pull rank here

Apology on using paranoid. I didn't realize it's a strong word. But I really hate pulling rank. If you have facts, feel free to convince me. Stop using non-related nonsense to proof something. It's logically meaningless.

I'm happy to quit this subject when there are many other things to do.

**Comment by mikemcquaid** [comment]
> Apology on using paranoid. I didn't realize it's a strong word. But I really hate pulling rank. If you have facts, feel free to convince me. Stop using non-related nonsense to proof something. It's logically meaningless.

That's OK, I appreciate the apology. I'll talk about the rest privately.

**Comment by geoff-codes** [comment]
I don't really want to get too involved here, but I'm 100% positive it can be done without any ruby whatsoever.

I'll have a proof of concept for you guys in ±24 hours.

**Comment by geoff-codes** [comment]
Yikes, just made it under the wire. Never promise to deliver code in 24 hours! :scream_cat:

**Comment by mikemcquaid** [comment]
Note that `brew update`'s no-op is now fast enough that I think we could do this (at least before every `brew install`).

**Comment by geoff-codes** [comment]
+1

I quite like what you've done with this, Mike.
I think you're right, and possibly several other commands as well, although you might want to consider backgrounding the updates of non-core taps for some of the lesser consequential subcommands?

**Comment by UniqMartin** [comment]
I think it would be sensible to limit auto-updates to at most once a day? That should keep the latency down when working with Homebrew, particularly for people with slow connections and for those who tap from locations that cannot benefit from the GitHub-specific optimization.

Another thing I'm slightly worried about is that the local installation will be in constant flux, so a build that succeeded in the morning will suddenly break in the afternoon (hopefully it's the reverse situation). Or, though that requires good timing, one uses `brew search` and `brew info` to gather information about a formula and by the time `brew install` is entered the formula is gone, e.g., because it was moved to the boneyard. But I guess the benefits still outweigh the potential issues described here.

**Comment by mikemcquaid** [comment]
> That should keep the latency down when working with Homebrew, particularly for people with slow connections

I can simulate slow local connections and I don't think an HTTP connection's worth of delay is going to be noticeable, really.

> those who tap from locations that cannot benefit from the GitHub-specific optimization.

I'd rather just handle this case specifically (e.g. autoupdate just them once a day) as that is by far the minority of uses.

> But I guess the benefits still outweigh the potential issues described here.

Yeh, this is one of those "I can see both sides but in terms of reducing our bug reports and long-term improvements for most users: it'll be a net win".

**Comment by MikeMcQuaid** [comment]
Migrated to https://github.com/Homebrew/brew/issues/288.
