### ISSUE TITLE
Use less jargon

### ISSUE THREAD

**Issue by MikeMcQuaid** [Homebrew/legacy-homebrew#41884]
e.g. `keg`, `tap`, `bottle`, `Cellar`, etc.

**Comment by chdiza** [comment]
In the end, the only thing that helps (if indeed anything helps) is documentation in an easy-to-find place or places.  I personally would like this stuff to go on the homepage and the man page.  We should just document what we already have, rather than change it only to have to carefully document it anyway.  It will save a lot of time and effort and we'll end up in the same place, namely, a place where users who read the docs will understand and the users who don't read the docs won't.  Also, it won't murder `git blame`.

I am willing to help improve our documentation of the existing terms.

**Comment by mikemcquaid** [comment]
Sorry but I disagree. Documentation is a solution for when you cannot avoid using jargon (e.g. every way of explaining requires jargon). We definitely do not need to use jargon in many of the places we do.

**Comment by dunn** [comment]
> users who read the docs will understand and the users who don't read the docs won't.

Yeah, I don't think those are the only possible outcomes.

**Comment by chdiza** [comment]
> Yeah, I don't think those are the only possible outcomes.

They are the only two relevant outcomes.  The other two possible outcomes are read-but-not-understand and not-read-but-understand-anyway.  The latter is irrelevant to the present issue, and *once our docs are optimized*, anyone who genuinely reads these hypothetical docs and still doesn't get it certainly won't be helped by any de-jargoning.  They will have deeper issues, like not understanding what `$PATH` is or what a symlink is, or they will confuse "won't be linked" with "can't be linked".

**Comment by scpeters** [comment]
I've always thought that the jargon is a fun part of the metaphor, but reducing user confusion should be a priority. Is this issue about reducing jargon in error messages or moving away from the metaphor entirely (i.e. will `/usr/local/Cellar` be changed to something like `/usr/local/HomebrewPackages`)?

**Comment by mikemcquaid** [comment]
@scpeters We'd keep jargon for internal naming (for now, at least)

**Comment by mxcl** [comment]
This isn’t documentation, these are the *names* of things. Names are hard. You have to pick something unique and explicit so that when you talk about it everyone understands what it is.

The reason I did not pick eg. package is because what is a package? In Package Management the word is thrown around to mean: the downloadable, or the installation, or the installation directory or the software-project.

If you must confuses tens of millions of people be renaming Homebrew *fundamentals*, at least pick words that are not *more* ambiguous. OK?

**Comment by xu-cheng** [comment]
Personally, I'm fine with this jargon as long as I can easily find a glossary in the document.

**Comment by mikemcquaid** [comment]
@mxcl Hey Max, hope you're well :wave:. Thanks for the feedback, will take it on board.

**Comment by MikeMcQuaid** [comment]
Migrated to https://github.com/Homebrew/brew/issues/290
