### ISSUE TITLE
python's sys.prefix points to a version-specific framework path

### ISSUE THREAD

**Issue by tdsmith** [Homebrew/legacy-homebrew#42236]
I'm hearing on IRC that this leads conda (and possibly virtualenv?) to do the wrong thing. I should discover what "the wrong thing" is and decide how bad it is.

We could override sys.prefix (and a matching exec_prefix probably?) in sitecustomize.py, like we do sys.executable, if we decide it's safe.

**Comment by tjnycum** [comment]
Thanks, Tim. For the sake of record here and reminder, the practical issue is that [conda](http://conda.pydata.org/docs/) uses `sys.prefix` as its "root environment", under which, by default, it'll store the created python environments, its package cache, and perhaps other things. (That can be overridden in an rc file, but unless a particular shell environment variable is set it'll look for the system-wide version of that file in... right, `sys.prefix`.) `sys.prefix` currently gets set to, for example, `/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4`, so unless the user takes several deliberate configuration steps to work avoid it, their conda state (incl. python environments) will be specific to each minor version of python, when it's intended to be independent of even major version.

**Comment by tdsmith** [comment]
I didn't realize conda stored things there; that's annoying. What are the configuration steps that allow users to store things elsewhere?

**Comment by tjnycum** [comment]
Due to Homebrew's git-tracking of /usr/local, you mean?

Well, to be honest I haven't fully worked that out and tested it. I've just now been trying to do that, but based on what I've been able to find—unfortunately conda's documentation isn't the most comprehensive or clear—I think you would at least lose some configuration functionality/flexibility, and the redirection might not even be completely effective (i.e. might not prevent it from using `sys.prefix` for something under some circumstances).

It appears you can tell it to store at least some things (e.g. environments) elsewhere in user and system .condarc files, which are YAML-formatted and manipulated through the [`conda config`](http://conda.pydata.org/docs/commands/conda-config.html) command (modeled after `git config`). The default location for the system .condarc file, though, is... `sys.prefix`. There's a CONDARC environment variable that it checks for, but my impression is that that makes it look for (and *require*) an RC file there and *only* there (not also checking for a user .condarc). So it doesn't simply change the location it uses for the system RC file. Also, as you may know, relying on environment variables in OS X can be [complicated and problematic](http://stackoverflow.com/q/135688/2917502).

**Comment by MikeMcQuaid** [comment]
We'll accept PRs for this but we're not actively working on it at this time.
