### ISSUE TITLE
Need better way to handle Luarocks

### ISSUE THREAD

**Issue by alerque** [Homebrew/legacy-homebrew#42273]
I have a nearly useless package formula and I can't figure out how to fix it because either A) Homebrew doesn't support Lua dependencies properly or B) I just can't figure out how to do it.

When I first submitted the SILE formula in #40893 I asked about how to handle these but didn't get much feedback and the formula was eventually merged with some bits like this:

    def install
        system "luarocks-5.2", "install", "lpeg"
        # ...
    end

Then later in I discovered I needed one more Lua rock and added it in #41288. At that point it was pointed out that the Lua deps were broken because the bottling process wasn't actually catching them. I was instructed to drop those lines in favor or an something like this:

    depends_on "lpeg" => :lua

This is great in theory, but in practice it means nobody that isn't already well versed in Lua or has their machine setup with it can actually install SILE. As reported in simoncozens/sile#143 users without Lua cannot even run the luarocks install command manually. It just doesn't work unless you've gotten it setup before. Because the formula aborts when it doesn't install ALL the dependencies, the user has to install Lua by itself first, then install the luarocks manually, then go on to install SILE. This is a disaster from a usability standpoint.

The biggest hold up seems to be the bottle system. It seems like I can get people a lot further by pointing people at a separate fork rather than the Homebrew version because by skipping the bottling step I can actually install the dependencies.

The current install procedure is a disaster from a usability perspective. So the question becomes:

1. Can I submit a version of this formula that does not get bottled and does install the luarocks?
2. Can the bottler be fixed so it actually includes these parts?
3. Can I create separate formulas for each needed rock and use them as dependencies (this is the way most Linux distros handle this)?
4. A better way?

**Comment by alerque** [comment]
@DomT4, you [mentioned before](https://github.com/Homebrew/homebrew/pull/41288#issuecomment-118508488) that the Lua dep system needed some help. Do you have any input into this? The way things are right now users are not able to get the software working at all. It works okay for people that have previously installed it manually because their systems have the deps, but for fresh systems they just can't make out what needs to be done.

**Comment by DomT4** [comment]
Hey, Thanks for the ping. There's a lot of things in play with this issue that are rubbing up against each other in less than helpful ways.

> you mentioned before that the Lua dep system needed some help.

Firstly, yeah, the big one, is that Homebrew's dependency resolution for Lua modules is terrible. This is partly because there's been *very little* desire from contributors to install Luarocks as part of a formula, or even require lua dependencies in general; we have maybe 60 formula which need either Lua or Lua51 out of ~3200 core formulae.

The other part is that Lua doesn't have someone who is both a maintainer & loves the software in the same way as @tdsmith does with Python. An enormous part of what makes Homebrew's handling of Python libraries (as resources) and applications (as formulae) such a pleasant experience is Tim. I've ended up as the go-to Lua guy, but as I've said before, Lua/Luarocks is neither my favourite nor best thing in the world.

Long-term, the answer is for someone who knows both Ruby and Lua at a high level to come along and offer to deal with the outstanding Lua issues in the same way Tim shook the Python handling up for the better.

> As reported in simoncozens/sile#143 users without Lua cannot even run the luarocks install command manually. It just doesn't work unless you've gotten it setup before.

This is one of the problems I'd like to get fixed relatively quickly. We should either make it clear that you need to install Lua to be able to install Lua dependencies, or change the dependency resolution so normal dependencies are fulfilled before special dependencies. It works well for `=> :python`, `=> :ruby` and `=> :perl` dependencies in the few places those still exist because those are shipped by default on OS X so nobody needs to install anything new, but obviously, that is not the case with Lua.

> The biggest hold up seems to be the bottle system. 

It's not, really. That is the short-term problem, but we're actually moving towards sandboxing installations so things aren't dumped into various places willy-nilly without Homebrew's knowledge, which we then lose control over and cause various problems like permission poisoning & not being able to remove those elements when the formula is uninstalled.

With the sandbox in place, you won't be able to write to `HOMEBREW_PREFIX` in general during the installation stage, just specific formula-related directories, which would break a direct `luarocks install xyz` in-formula element.

> Can I submit a version of this formula that does not get bottled and does install the luarocks?

Per the above, sadly not.

> Can the bottler be fixed so it actually includes these parts?

Luarocks are rather specific & grumpy about where they would like to be placed. Because of the way this specific formula checks for Lua modules installed *during* the configure script, it's essentially impossible within Homebrew because we don't link anything into the main `HOMEBREW_PREFIX` until installation is complete.

Requiring modules to be installed before installation is somewhat tricky behaviour, and upstream would make our lives significantly easier if instead of checking for those modules during configure they'd move that check into the executable, so instead of breaking during configure it'd install and then on run throw a message like `You need to install xyz module`. If that was the situation, we could hack together some sort of `postinstall` solution which would do something like `luarocks install xyz` for the user (Resolving your immediate issue/concerns).

In the end, adopting a Pythonesque system where we append things in `libexec/vendor` & the formula executables to a `LUAPATH` is likely the solution, but we're not at that point yet and to be honest, unless someone steps up to do it, it isn't going to happen quickly. It's a lot of work to get done correctly.

> Can I create separate formulas for each needed rock and use them as dependencies (this is the way most Linux distros handle this)?

I'm not actually against this, but Homebrew has a firm rule on not accepting Python/Perl/etc *libraries* as formulae, and I don't think we should open the floodgates on bending that rule, so that immediately limits how much we could turn into formulae. There still remains the problem that Luarocks/Lua is very specific about where things should be installed and that's difficult to work around without a lot of hackery.

**Comment by mikemcquaid** [comment]
Agreed with all that @DomT4 :+1:

**Comment by alerque** [comment]
@DomT4 Thanks for continuing to look into this. I have a question about this bit of your last overview comment:

> Requiring modules to be installed before installation is somewhat tricky behaviour, and upstream would make our lives significantly easier if instead of checking for those modules during configure they'd move that check into the executable, so instead of breaking during configure it'd install and then on run throw a message like You need to install xyz module. If that was the situation, we could hack together some sort of postinstall solution which would do something like luarocks install xyz for the user (Resolving your immediate issue/concerns).

Isn't that exactly what configure is _supposed_ to do? In the Unix world it runs these checks specifically to see if it's going to have everything it needs up front. I'm not inclined to change than behavior because it would stop serving its correct purpose and potentially introduce errors for Linux package managers. On the other hand we _can_ mess with the upstream here (possibly introducing Homebrew specific upstream stuff) if that will make one step installation possible for OSX users. I can work on that, but another thought would be to add a patch to the formula. That way it would be very clear when updating the formula what was going on. A patch could strip out the offending lines and the one-to-one relationship between the stripped lines and the dependencies manually installed by the Formula ought to be obvious. It would also leave the upstream in the most reasonable state for manual installations and if and when Homebrew does support this properly it would be more natural to revert it in the Formula that to have to go upstream again.

Does that approach make any sense to you?

**Comment by mikemcquaid** [comment]
> On the other hand we can mess with the upstream here (possibly introducing Homebrew specific upstream stuff) if that will make one step installation possible for OSX users. I can work on that, but another thought would be to add a patch to the formula. That way it would be very clear when updating the formula what was going on. A patch could strip out the offending lines and the one-to-one relationship between the stripped lines and the dependencies manually installed by the Formula ought to be obvious. It would also leave the upstream in the most reasonable state for manual installations and if and when Homebrew does support this properly it would be more natural to revert it in the Formula that to have to go upstream again.

Just FYI that Homebrew doesn't really accept long-lived patches that will never be merged upstream as the risk of us inadvertently introducing new bugs is relatively high.

**Comment by alerque** [comment]
@mikemcquaid I understand the logic there — if what you are doing is fixing bugs or adding features or changing behavior of upstream software. I've maintained dozens of packages for two Linux packaging systems for a decade now; I'm no stranger to the woes of dealing with downstream patches.

But I'm not sure that logic applies here. This isn't an upstream bug. The dependency checking is not, as far as I can figure, broken in the upstream code. In fact it's quite standard and _the way it should be_ for stand alone compiling and for packaging on other systems. The thing that is broken here is Homebrew. Homebrew doesn't properly handle this otherwise standard scenario. This is a normal library dependency and Homebrew has no features for packaging libraries in this language nor for facilitating them being handled.

The reason I don't think doing this upstream makes much sense is because there isn't anything _wrong_ upstream and this isn't an issue anywhere but Homebrew. I suggested a patch because what we're trying to make up for here is the fact that Homebrew is leaving users high and dry and expecting them to go do something manually that _could_ be scripted and _should_ logically be handled by a package manager.

The "upstream" that needs to be fixed in this case is Homebrew, not SILE. When functionality to handle dependencies is "merged upstream" the sort of patch I'm recommending could be removed.

I am a SILE contributor and am happy to facilitate an upstream change if such would be beneficial to the project across any packaging system, but it makes more sense to me to fix it where it is broken: here. The lifetime of such a patch would be until Homebrew has more full featured handling for this language and library dependency situation.

**Comment by DomT4** [comment]
I'll jump back into this discussion at some point later today. Once I round out the final syntax and sometimes-but-never-consistently-triggered error in #42576 it will at least become more obvious that you need to install xyz with `brew` before you can do `luarocks install xyz`, which resolves at least one chunk of confusion from the SILE thread.

**Comment by mikemcquaid** [comment]
> But I'm not sure that logic applies here. This isn't an upstream bug. The dependency checking is not, as far as I can figure, broken in the upstream code. In fact it's quite standard and the way it should be for stand alone compiling and for packaging on other systems. The thing that is broken here is Homebrew. Homebrew doesn't properly handle this otherwise standard scenario. This is a normal library dependency and Homebrew has no features for packaging libraries in this language nor for facilitating them being handled.

Sure, that's cool. I'm just uncomfortable with us accepting patches to third-party code here. We should fix our own code rather than that of other people (which we are more likely to screw up) :+1:

**Comment by alerque** [comment]
Any progress on this front? If there is anything we can change upstream to make this package easily installable through Homebrew I'd like to get it taken care of soon before we roll the next point release so that we can test and make sure things go smoothly on the install front before 1.0.0.

**Comment by mikemcquaid** [comment]
@alerque I'm not sure I personally understand how this is actionable. @DomT4 may be working on it at some stage but, like all Homebrew maintainers, his TODO list is pretty long so we'll need to rely on community contributors to submit fixes to improve the situation until then.

**Comment by daurnimator** [comment]
See my reply at https://github.com/Homebrew/legacy-homebrew/issues/35787#issuecomment-69649766

**Comment by MikeMcQuaid** [comment]
Closing old usability issues in favour of pull requests.
