### ISSUE TITLE
G++ Internal compiler error

### ISSUE THREAD

**Issue by Goobley** [Homebrew/legacy-homebrew#43001]
I have just experienced an ICE and the error message told me to report it here - if you want me to pass it on to GNU through GNAT instead then let me know.

The bug is related to compiling with link-time optimisation in g++ 5 compiled from source without multilib from Homebrew

The details I have so far are in this StackOverflow [post](http://stackoverflow.com/q/32037069/3847013), I haven't yet been able to create a minimal example and I can upload the preprocessed sources if desired, but they are ~15-20k lines before preprocessing which is probably not very useful to you. I can confirm that the error only occurs at link-time whether I use the apple provided llvm linker or let g++ choose its linker.

**Comment by UniqMartin** [comment]
Sorry that we failed to get back to you in a timely manner! I suspect the issue has been fixed a long time ago, as there have been multiple point releases of GCC since then. If not, an internal compiler error is unlikely something Homebrew maintainers will be able to help with, so it's best to report that upstream.
