### ISSUE TITLE
Error installing git on Lion

### ISSUE THREAD

**Issue by ParaPenguin** [Homebrew/legacy-homebrew#43332]
Encountered while trying to install git 2.5.0 on Mac OS Lion (10.7.5).

```
==> make install prefix=/usr/local/Cellar/git/2.5.0 sysconfdir=/usr/local/etc CC
make: *** [git-add--interactive] Error 2
make: *** Waiting for unfinished jobs....
make[2]: *** No rule to make target `/System/Library/Perl/5.12/darwin-thread-multi-2level/CORE/config.h', needed by `perl.mak'.  Stop.
make[1]: *** [instlibdir] Error 2
make: *** [git-difftool] Error 2
```

I saw a similar error to that in #7091, but I am unsure if this is the exact same issue.

**Comment by dunn** [comment]
Can you post `brew gist-logs git`, please?

**Comment by ParaPenguin** [comment]
@dunn https://gist.github.com/dd43b757578ce7f52f1f

**Comment by UniqMartin** [comment]
This might be resolved as `git` has seen numerous updates since then. If not, I'm sorry if there's no solution for this, but I'm closing this issue anyway. 10.7 is fairly old and no longer officially supported by Homebrew  (as indicated by the output that `brew doctor` provides). We'll happily accept PRs that improve the situation for older OS X releases, but resolving this ourselves is not a priority for us. Thanks for understanding!
