### ISSUE TITLE
brew desc -d returns wrong results (brew debug)

### ISSUE THREAD

**Issue by denji** [Homebrew/legacy-homebrew#43864]
Problem when searching by description (`-d`), it show the debug-mode homebrew
```
desc  [-s|-n|-d]
      <pattern>:
      Search both name and description (-s),
      just the names (-n),
      or just the descriptions (-d) for <pattern>.
```

`brew desc -d pgloader` – debug mode brew-ruby, but search description is not working
`brew desc -s pgloader` – searches for substring in name formula too (unnecessary results)

**Comment by xu-cheng** [comment]
We probably need to choose a better flag than `--description`.

**Comment by apjanke** [comment]
> brew desc -d pgloader – debug mode brew-ruby, but search description is not working

The description search does seem to be working. This particular search produces no output because the string "pgloader" doesn't appear in any formula descriptions.

```
$ brew desc -d pgloader
$ brew desc -d PostgreSQL | grep pgloader
pgloader: Data loading tool for PostgreSQL
```


About the debugging output:

It looks like this is because the Homebrew extension `ARGV.flag?` logic allows collisions for single-letter option names. The `-d` looks like both `--description` and `--debug` if it's asking with `flag?`.

`formulary.rb` [checks for a debug option with `ARGV.debug?`](https://github.com/Homebrew/homebrew/blob/433aa72b1ecfea67146bb29541ed53d23f351c9f/Library/Homebrew/formulary.rb#L81)

```
 STDERR.puts "#{$0} (#{self.class.name}): loading #{path}" if ARGV.debug?
```

which in turn [uses `flag?`](https://github.com/Homebrew/homebrew/blob/433aa72b1ecfea67146bb29541ed53d23f351c9f/Library/Homebrew/extend/ARGV.rb#L103-L105)

```
  def debug?
    flag?("--debug") || !ENV["HOMEBREW_DEBUG"].nil?
  end
```

which in turn [uses a substring](https://github.com/Homebrew/homebrew/blob/433aa72b1ecfea67146bb29541ed53d23f351c9f/Library/Homebrew/extend/ARGV.rb#L183-L185) to automatically recognize the single-letter form of the option.

```
  def flag?(flag)
    options_only.include?(flag) || switch?(flag[2, 1])
  end
```

So a `-d` in any command that uses the formulary classes will be seen as `--debug` in addition to whatever other meaning it has, and turn on debugging output.

Since `-d` is not documented in `man brew` as enabling debug output, maybe that's what should be changed, and the formulary debug output test changed to only recognize the full `--debug` flag and not `-d`, too.

**Comment by xu-cheng** [comment]
> Since -d is not documented in man brew as enabling debug output, maybe that's what should be changed, and the formulary debug output test changed to only recognize the full --debug flag and not -d, too.

Sorry, I disagree this. `-d/--debug` and `-v/--verbose` have been existed for long time and used in multiple brew commands as well as external brew commands. I think it is `--description` should be changed.

**Comment by apjanke** [comment]
We should probably document `--debug` in the man page as applying to additional commands, then. Right now, `--debug` is only listed under `install` and `test`, and only with respect to opening an interactive shell upon failure, not enabling additional output.

Maybe it should be added to the main `brew` synopsis, where `-v/--verbose` is documented now? Like this:

```
       brew --version
       brew command [--verbose|-v] [--debug|-d] [options] [formula] ...
```

**Comment by xu-cheng** [comment]
I'm :+1: for adding `-v/-d` to document. cc @Homebrew/owners for opinions.

**Comment by bfontaine** [comment]
I’m :+1: on this too.

**Comment by denji** [comment]
@xu-cheng Perhaps it would be better flag `--desc` (`--description`)

**Comment by DomT4** [comment]
> I'm :+1: for adding -v/-d to document.

Agree with this.

**Comment by apjanke** [comment]
PR for adding it: #44762

**Comment by MikeMcQuaid** [comment]
This is better documented now.
