### ISSUE TITLE
pkg-config files point to versioned source

### ISSUE THREAD

**Issue by hgaiser** [Homebrew/legacy-homebrew#44272]
I noticed something strange in the pkg-config files generated by brew(?), they point to the exact version of the package. For example pkg-config files point to "/usr/local/Cellar/package/version/include" instead of the symlinked "/usr/local/include/package". This caused an error on my system with a generated cmake file based on the pkg-config output. Had it point to /usr/local it would have worked fine.

ps. I wasn't quite sure where to report this, hope this is the correct place.

**Comment by DomT4** [comment]
What issue were you seeing exactly? Can you provide a way for us to reproduce this error?

`brew` doesn't actually generate 99.9% of the `.pc` files itself, that happens automatically by the upstream project because it uses the `prefix` argument to determine the pointed to prefix. We can't arbitrarily override those files because there's plenty that isn't symlinked into `HOMEBREW_PREFIX` and would break.

**Comment by hgaiser** [comment]
I see, I assumed brew was the one generating the pc file.

The issue occurred with eigen3. I had 3.2.4 when I installed ROS. ROS generates some cmake files based on pkg-config output, so it used /usr/local/Cellar/eigen3/3.2.4 as the path to Eigen. I then updated and removed old versions. Eigen was now located in /usr/local/Cellar/eigen3/3.2.5 so the packages that used the generated cmake from ROS no longer worked.

I now regenerated these cmake files, which of course worked, but it would be cleaner if pkg-config gave me the path in /usr/local/include instead.

**Comment by DomT4** [comment]
Not directly, no. We just install the `pkg-config` files the upstream project generates in the compile stage. We sometimes write our own, but it isn't commonplace by any means.

I'm not convinced there's much we can do here that's sensible, sadly. We shouldn't take up mass rewriting `pkg-config` files, in part because there's things we don't symlink into the top-level prefix which would instantly break, and I'm not sure there's much love for adding another override switch to the core code.

I'd suggest if you need static links that you either feed `cmake` the paths to the dependencies by pointing directly at a top-level path, which is usually an option, or write your own temporary pkg-config files and prepend the `PKG_CONFIG_PATH` with those prior to compile. You can also `brew pin` dependencies to stop them being updated.

I'll leave this open for today in case another maintainer wants to discuss merits of rewriting `pkg-config` files to the top-level directory.

**Comment by tdsmith** [comment]
Replacing prefix with opt_prefix in .pc files ought to be safe. I guess this is only an issue for things that remember pkg-config output and I'm not sure how common those are.

**Comment by DomT4** [comment]
I don't have a particular objection to overwriting the prefixes with the opt path, but am hesitant to do mass pkg-config rewriting unless we absolutely have to.

**Comment by MikeMcQuaid** [comment]
We'll accept PRs for this but we're not actively working on it at this time.
