### ISSUE TITLE
Unable to do `brew gist-logs` for certain formulas

### ISSUE THREAD

**Issue by jakobmoss** [Homebrew/legacy-homebrew#44706]
I am unable to do `brew gist-logs openblas`, but it works fine for e.g. numpy:
```
> brew gist-logs openblas
Error: HTTP 405 Not Allowed (expected 201)

> brew gist-logs numpy
https://gist.github.com/395e936b764b4e9ce87c

> brew gist-logs openblas
Error: HTTP 405 Not Allowed (expected 201)
```
When looking at my gists, it seems that the gist of openblas is actually created, but is somehow to large (the message *This file has been truncated, but you can view the full file* is displayed)? But if I try to open the gist, I am presented with a unicorn telling me, that *this page is taking way too long to load*.

**Comment by xu-cheng** [comment]
It's a known issue that `brew gist-logs` will fail if the log is too large.

**Comment by apjanke** [comment]
I get the same thing. Those log files are under GitHub's [100 MB limit](https://help.github.com/articles/working-with-large-files/).

It looks like the Gists are created okay for me too, even though I get an error back. You can still get at the gists if you go to their URL, like https://gist.github.com/apjanke/90a2d9503fab3716775b, and then just slap a `/download` on the end of it, like https://gist.github.com/apjanke/90a2d9503fab3716775b/download. Then you'll get the whole gist as a tarball, and it's still usable for debugging. (More useful, IMHO; the gist viewer sucks for multiple long files.)

Maybe `gist-logs` should still report the URL to the user when that `405` happens, possibly adding the `/download` automatically.

**Comment by mikemcquaid** [comment]
> Maybe gist-logs should still report the URL to the user when that 405 happens, possibly adding the /download automatically.

:+1:

**Comment by jamandbees** [comment]
I was working on reproducing this with curl to see what happens differently when you receive the 405 vs not getting the 405.

How the URL is retrieved is that github sends back some JSON upon successfully posting a gist. You can reproduce this pretty trivially with the following curl command:

`curl -X POST --data "{\"description\":\"Created via API\",\"public\":\"true\",\"files\":{\"test.txt\":{\"content\":\"testing\"}}" https://api.github.com/gist`

First, I wanted to see if it's easily feasible to retrieve the gist URL upon a 405. I first created a tiny json file and then tried to POST it:

```
[james@greentreeredsky Homebrew]$ cat !$
cat json_template
{"description":"Created via API","public":"true","files":{"template":{"content":"template"}}}
[james@greentreeredsky Homebrew]$ curl -i --user "jamandbees" -X POST --data-binary "@./json_template" https://api.github.com/gists
```

It posts just fine. Then I replaced the content above with 100 meg of zeroes. To create that, I used:

```
[james@greentreeredsky Homebrew]$ dd if=/dev/zero of=100_meg_nuls.txt bs=1024 count=102400
102400+0 records in
102400+0 records out
104857600 bytes transferred in 0.366705 secs (285945425 bytes/sec)
[james@greentreeredsky Homebrew]$ tr < 100_meg_nuls.txt '\000' '0' > 100_meg.txt
[james@greentreeredsky Homebrew]$ du -sh 100_meg.txt
100M	100_meg.txt
[james@greentreeredsky Homebrew]$ wc 100_meg.txt
       0       1 104857600 100_meg.txt
```

I used vi to insert 100_meg.txt into json_template, replacing the word "template" with the 100 megs of zeroes, then I used curl to try and post the gist. I posted it to my user account, so I could find it a little more easily. The result is:

```
[james@greentreeredsky Homebrew]$ curl -i --user "jamandbees" -X POST --data-binary "@./100_meg.json" https://api.github.com/gists
Enter host password for user 'jamandbees':
HTTP/1.1 100 Continue

HTTP/1.1 405 Not Allowed
Server: GitHub.com
Date: Fri, 20 May 2016 14:45:36 GMT
Content-Type: text/html
Content-Length: 166
X-GitHub-Request-Id: 43B03DB5:1271B:AEBFA14:573F22AF

<html>
<head><title>405 Not Allowed</title></head>
<body bgcolor="white">
<center><h1>405 Not Allowed</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

You don't have a JSON blob to retrieve the URL for the gist. I don't think it's feasible to easily retrieve the gist URL upon a 405. You could _try_ to retrieve it by doing some scraping and whatnot, but then you're probably going to enter into a world of pain for public gists because multiple people can be posting gists simultaneously around the world.

Given that GitHub are trying to actively prevent 100 meg and larger files from being posted, and the current behavior that the Gist is created is actually a bug that they could patch at any time, I think HomeBrew would be better off giving a warning that some log files are too large to post to a Gist, but whatever's smaller than 100 meg could be posted.

**Comment by apjanke** [comment]
Thanks for doing the legwork on this.

> Given that GitHub are trying to actively prevent 100 meg and larger files from being posted, and the current behavior that the Gist is created is actually a bug that they could patch at any time, I think HomeBrew would be better off giving a warning that some log files are too large to post to a Gist, but whatever's smaller than 100 meg could be posted.

This is sounding pretty reasonable to me. Seems like we should respect their limits instead of try to circumvent them.

Maybe what we could do in this case is custom truncation of the log files to try to get under 100 MB – say, cut out the middle of any file over 50 MB to get it down to, say, 40 MB, or even 10 MB. Sort of like what we do with `brew test-bot` build output. That would probably let most log sets be posted, since really big logs tend to be just one big file that's the output of `make`. And most of that spew isn't relevant to the error, which will probably crop up at the end of the file, so truncated log sets would still be useful for diagnosis.

Let's ask GitHub support. I've sent them a request asking them to clarify the Gist size limit behavior, and whether there are undocumented limits we should be respecting, etc. Will post any response. But I think in the mean time, we should consider the 405 error to really mean "please don't do that", so we should check our log sizes and either balk on the upload or truncate them.

**Comment by jamandbees** [comment]
GitHub already documents the 100mb limit (https://help.github.com/articles/conditions-for-large-files/ - the key is realising that Gists are actually git repositories under the hood). The article reads like trying to push large files with git generates a slightly more user-friendly warning, though I've not tried that out. Although the article covers larger files, I think the Git LFS stuff requires being in a git repository. I can't think of any way to take advantage of that.

I can write a path that'll attempt to truncate logs before uploading, but I'm not sure what would be useful to drop and what to retain. Instinctively, I could grab the first 25 megabytes and the last N megabytes that'd take you up to a hard limit of 50 megabytes. Would that work? Otherwise, I can also just write the patch that'll check log file sizes and bail if they're greater than about 95 megabytes (I noticed with curl that 99 megabytes fails consistently as well, so we'd need to be a few megabytes smaller than the limit to be safe).

As it stands, incidentally, I think keeping the log file sizes small is pretty wise. Gist-logs uses okjson to validate its json, but in doing so there's a case statement run against every single _character_ in the files which makes gist-logs really, really slow for files larger than a few megs. The slowness is to the point where I was thinking of either creating a patch that has a warning about potential slowness when log files are above about 10 megabytes, or seeing how hard it would be to switch json libraries to something with a lower performance overhead. I'd be happy to write an issue for that if  it sounds like a good idea.

**Comment by apjanke** [comment]
Thanks! Didn't know where to look. That makes sense.

> I can write a path that'll attempt to truncate logs before uploading, but I'm not sure what would be useful to drop and what to retain. Instinctively, I could grab the first 25 megabytes and the last N megabytes that'd take you up to a hard limit of 50 megabytes.

I would do something like first 2 MB + last 8 MB for each individual log file over 10 MB. (Build log sets may have multiple large files, so that gives us a margin of safety.) Builds usually bail when there are errors, so the later parts of the log are more likely to be useful, and intermediate parts of large logs typically less so. And then warn at the end if the total upload size is still too big.

Just truncating the logs at 10 MB per file (or even less) could help with the validation speed, too. Because JSON is UTF-8 (IIRC) and the structure is context-sensitive, the validation probably has to be done character-wise, and other libraries may not be any faster.

I need to read up on the `gist-logs` implementation code before giving any more detailed feedback (e.g. whether truncation needs to be done character-wise to preserve UTF-8 validity or to treat the log files as binary/"8-bit ASCII" instead, etc). I'll try to do so tonight if I have time.

**Comment by apjanke** [comment]
Here's an idea: it looks like Git LFS supports large file pointers in Pull Requests. Perhaps large file support could be added to `gist-logs` by having the logs posted as Pull Requests on a dedicated `brew-build-logs` repo instead of as Gists. Because Homebrew controls the installation process, we could ensure that the Git LFS client is installed with Homebrew.

But I dunno if that's worthwhile: I don't think I've ever seen a case where the full log output for large build logs was actually useful in a way that truncated-to-10-MB logs wouldn't have been. Truncation would be a lot simpler to implement and support.

**Comment by MikeMcQuaid** [comment]
> But I dunno if that's worthwhile: I don't think I've ever seen a case where the full log output for large build logs was actually useful in a way that truncated-to-10-MB logs wouldn't have been. Truncation would be a lot simpler to implement and support.

Agreed on this.

**Comment by apjanke** [comment]
I heard back from GitHub support on this, saying that the 405-error-but-actually-successful-upload behavior was a surprise to them, and shouldn't be relied on, and they asked that encouraged us to keep Gist uploads to "a few megs".

Even if Gists allow uploads of up to 10 MB, if they're under that threshold but still large, you'll get a "unicorn" error page saying "this page is taking too long to load" when trying to view them on `gist.github.com`. And it's kind of a pain to manually fiddle with the URL to get the zip file download. If we're going to be using Gists for logs, I think maybe our goal should be to get them small enough that they can load in the normal Gist web interface, with no unicorns.

(I'm fiddling around with a truncating `gist-logs` branch right now, and still getting unicorns at about 4 MB of gist log content. 1-2 MB seems fine.)

**Comment by apjanke** [comment]
Here's a PR to do the truncation: https://github.com/Homebrew/brew/pull/279

**Comment by apjanke** [comment]
For reference, this is from Ivan Zuzak at GitHub Support:

> I was able to reproduce the 405-error-but-actually-successful upload behavior for gists with files over 100MB. The 405 is indeed strange and confusing, and something the team is already investigating. I think those might be related to some time-based limits we have on all requests.
>
> To answer your question -- Gist currently doesn't enforce the strict size limits like repositories on GitHub do, but we expect that will happen at some point in the future. For that reason, we'd like to encourage you to pick a different solution for hosting such large log files (such large logs are well above average usage), and keep the files you upload as gists to a few MB.
