### ISSUE TITLE
Tesseract: install denied although conflict is about optional package

### ISSUE THREAD

**Issue by eject-it** [Homebrew/legacy-homebrew#44851]
$brew info tesseract
    tesseract: stable 3.04.00 (bottled), HEAD
    OCR (Optical Character Recognition) engine
    https://github.com/tesseract-ocr/
    Not installed
    From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/tesseract.rb
    ==> Dependencies
    Required: leptonica ✘
    Recommended: libtiff ✔
    ==> Options
    --all-languages
	Install recognition data for all languages
    --with-opencl
	Enable OpenCL support
    --with-training-tools
	 Install OCR training tools
    --without-libtiff
	Build without libtiff support
    --HEAD
	 Install HEAD version

Well, OK. Lets go ahead.

    $brew install tesseract --without-libtiff
    Error: You must `brew link libtiff' before tesseract can be installed

If you insist. I think it is non of your business. 

    $brew link libtiff
    Linking /usr/local/Cellar/libtiff/4.0.6...
    Error: Could not symlink share/man/man1/bmp2tiff.1
    Target /usr/local/share/man/man1/bmp2tiff.1
    already exists. You may want to remove it:
    rm '/usr/local/share/man/man1/bmp2tiff.1'

I'm sorry Love, that is not gonna happen.

If you ask for the dry run list in force override mode the whole conflict is about man files it isn't supposed to install or link anyway. 
Why are there no options to simply tell homebrew to shut up and go ahead anyway?

**Comment by mikemcquaid** [comment]
Is this a feature request, bug report or neither?

**Comment by eject-it** [comment]
I'd consider it a bug. Why does it need to link a resource that is not chosen?  Why does it even look for it? 
In the end I don't care. That is up to the guys making the decision of how Homebrew should behave. If this behaviour is intended, fine with me.  I just had a few minutes while compiling from scratch.
In any case Homebrew stays a comprehensive library for stuff that can be made to run on a mac.

**Comment by mikemcquaid** [comment]
Ok, I think I see. The issue is with our dependency resolution.

**Comment by skavie** [comment]
Hello! Brew install led me here... but not sure if it's exactly the same issue? 

$brew install --with-training-tools tesseract
==> Downloading https://github.com/tesseract-ocr/tesseract/archive/3.04.00.tar.g
Already downloaded: /Library/Caches/Homebrew/tesseract-3.04.00.tar.gz
==> ./configure --prefix=/usr/local/Cellar/tesseract/3.04.00
Last 15 lines from /Users/andygan/Library/Logs/Homebrew/tesseract/01.configure:
checking host system type... x86_64-apple-darwin14.5.0
checking --enable-graphics argument... yes
checking --enable-embedded argument... no
checking --enable-opencl argument... no
checking --enable-visibility argument... no
checking --enable-multiple-libraries argument... no
checking whether to use tessdata-prefix... yes
checking whether to enable debugging... no
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... configure: error: in `/private/tmp/tesseract20151105-28165-13qersx/tesseract-3.04.00':
configure: error: cannot run C++ compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details

READ THIS: https://git.io/brew-troubleshooting

These open issues may also help:
Tesseract: install denied although conflict is about optional package https://github.com/Homebrew/homebrew/issues/44851

Any ideas? New bug? Or user error?

**Comment by DomT4** [comment]
@skavie Unrelated. Would you mind opening a new issue with `brew gist-logs tesseract`? Thanks!

**Comment by apjanke** [comment]
Looks like there's a couple things going on here.

The first is that formula options like `--without-libtiff` aren't passed along to dependencies when recursively expanding the dependency tree. Though I couldn't find it documented, I suspect this is by design, since you generally wouldn't want an option for a single formula to apply to the entire dependency tree, the contents of which you might not know. What's happening here is that the `libtiff` dependency for `tesseract` is being ignored. But `tesseract` depends on `leptonica`, which itself has a `:recommended` dependency on `libtiff`. That's where it's being picked up, because the `--without-libtiff` doesn't apply to `leptonica` when it's pulled in as a dependency.

You can work around it in this case by explicitly including `leptonica` in the installation command: `brew install tesseract leptonica --without-libtiff`.

It'll still fail with the same error if you have already done a `brew install leptonica --without-libtiff`. The check for un-linked dependencies is done [in `check_install_sanity`](https://github.com/Homebrew/homebrew/blob/025ab1144f7cb26f9e80d4736c44bc170736f16f/Library/Homebrew/formula_installer.rb#L143-L153), which is done against `formula.recursive_dependencies` with no filter so it only looks at the default options, instead of `compute_dependencies(formula)`, which will take in to account the build options used for formulae which are already installed. This part sounds like a bug; seems like all the dep checks should be done against the installed-options-aware `compute_dependencies`.

> Why are there no options to simply tell homebrew to shut up and go ahead anyway? 

This can be done with `--ignore-dependencies`, once you have `leptonica` installed. You can see other options for `brew install` in `man brew`; only formula-specific options are listed in the `brew info` output.

**Comment by MikeMcQuaid** [comment]
We'll accept PRs for this but we're not actively working on it at this time.
