### ISSUE TITLE
Zsh-`bashcompinit` support for bash completions

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [Homebrew/legacy-homebrew#44910]
So, apparently recent Zsh versions support use of most *bash* completions. Perhaps a methodology could be provided where, when Homebrew currently notes the installation of a bash-completion script, it could also note an instruction for Zsh users to install the completion with `bashcompinit`?

**Comment by ELLIOTTCABLE** [comment]
It's important to note that some of these provide completions for *both* bash and Zsh; we don't want Zsh users overriding any more-powerful Zsh-specific completions with generic bash ones when both exist. I'm not sure how to go about this: perhaps a command to alias bash-only completions from `etc/bash_completion.d` into `share/zsh-completions`? For instance, we wouldn't want `etc/bash_completion.d/lein-completion.bash` overriding `share/zsh-completions/_lein`.

Yeah, really not sure what the most user-friendly way to go about this is. Input welcome? :D

**Comment by bfontaine** [comment]
> support use of **most** bash completions

How do we know *which* Bash completions are supported? :smile:

**Comment by ELLIOTTCABLE** [comment]
@bfontaine perhaps allow the formula author to vet that? Make notification-of-zshable-completions an opt-in thing?

**Comment by bfontaine** [comment]
It’s probably simpler to install (or symlink) the completions both in the Bash and the Zsh folder.

**Comment by apjanke** [comment]
I think we should differentiate between three cases here:

a) a completion definition shell script which itself is written to be portable between bash and zsh (and may have zsh-specific support)
b) an ordinary bash completion script which zsh could load using its `bashcompinit` completion portability layer
c) a conventional zsh completion function definition

Are there any specific cases of a) here? Or are you mostly considering the b) case that can be pulled in with `bashcompinit`?

Distinguishing between these probably needs to be done on a case-by-case basis by the formula maintainers. (And even then, it may be hard to tell what it is; completion support is sometimes an afterthought in other projects.) Bash and portable bash/zsh completions are generally loaded differently from conventional zsh completions: you source the bash style ones at startup time, but use `autoload` for the zsh-native ones and let the completion system call them lazily (which is set up by `compinit`).

For b), since `zsh` is just giving you a bash completion adapter, sounds like you may as well just leave them in the existing `bash_completion.d` location and let zsh load them from there. That's where zsh users using the bash completion portability layer would be looking for them anyway.

`site-functions` is the conventional place to put zsh completion definitions, at least by zsh's own conventions. The `#{prefix}/share/zsh-completions` directory looks like a Homebrew-specific convention. (The `zsh-completions` project doesn't provide its own support for deployment or installation; they just have a README that says "here, add this stuff to your `$FPATH`".) In our current setup, the zsh completions provided by the `zsh-completions` formula are installed to `share/zsh-completions`, and zsh completions provided as accessories by other formulae (like `git`, `hg`, `hub`, etc) are installed to `share/zsh/site-functions`. (I think.)

Advanced zsh users are going to have their own zsh configuration setup, including completion configuration. We should probably be conservative and err on the side of doing less, and letting the zsh users configure against it. For example, Oh My Zsh and related zsh configuration layers have logic that recognizes Homebrew and its paths, and will pick up zsh definitions and other tools like `autoenv` from there.

Because you have to invoke them differently, it might be nice to have two separate locations for the "portable" completions and the zsh-native completions, so a user could enumerate the ones that need to be loaded explicitly vs lazily-loaded via `compinit`, and set them all up dynamically inside their `.zshrc`.

**Comment by apjanke** [comment]
Put another way: `zsh` is really flexible, but is Some Assembly Required, and needs configuration. So a lot of zsh users have extensive `.zshrc`s or use a configuration layer like OMZ or Prezto. There's no single Right Way to do completion configuration, so we should probably defer most of that to the zsh-specific config layers, which specialize in that. It would be really hard to come up with a concise couple sentences for Caveats that instructed users how to enable completion that was appropriate for all users.

Since it takes extra work to set up, and can be complicated, maybe "Setting Up Shell Completion Support" deserves its own documentation page that describes the installation locations, how to configure your shell to use them, and has a couple external references.

The way the installation dirs are laid out now seems all right to me. Maybe stick with how they are for now, document it, and maybe have Caveats include a pointer to it for formulae that install zsh or bash completions.

**Comment by ELLIOTTCABLE** [comment]
Okay, some thoughts and responses to that:

1. It's a pretty important point that in addition to the possible cases you listed, there's *also* the possible (and common) case of *completely Zsh-incompatible* bash completions. [Call that α)? :P] That's, in fact, the primary problem here: we can't just add the bash folder to the `$fpath` or whatever; simple solutions are right out, because as far as I can tell, users have to manually vet each bash completion, and (this is crucial) require each one *individually* in their Zsh configuration. That's un-fun, and a mess. :P

2. I'm all for leaving the specifics up to OMZ or a wiki-page, if they end up being complex; but I'm not sure if I see why that's necessary? They *shouldn't* be complex; it should really boil down to adding a single line to your configuration, adding a single Homebrew `share` directory to your `$fpath`, at least for Zsh-specific completions. For bash ones, perhaps we could at least add ones vetted by formula-maintainers to a new, bash-to-zsh-compatible directory? (`etc/bash_completion.d/zsh-compatible`? or perhaps `share/zsh/site-functions/bash`?); then I'm not against leaving it up to OMZ or a wiki-page's instructions to actually *consume* those. (A printed mention of that page on package-install for users who have Zsh installed would be nice, too, I suppose, but not crucial: if you want this, presumably, you're going looking for it.)

3. And I'm now realizing that this is actually a separate issue, but since we're already talking about it here: ignoring Bash compatibility completely … why does the average Zsh user have *two* Homebrew-configured site-functions directories to set up? I understand that it's Homebrew convention to have `share/{package_name}/blah`; but is there a good reason we can't special-case the `zsh-completions` package to install directly into `share/zsh/site-functions`, instead?

(Oh, and regarding your earlier question: I haven't personally seen any examples of your **A**; it's **B**, **C**, and my **α**, that I see regularly: bash-specific scripts that `bashcompinit`'s shims successfully enable; more complicated ones that seem to fail anyway; and zsh-specific functions.)

**Comment by apjanke** [comment]
1. Having zsh-incompatible bash completions on `$fpath` is probably fine in and of itself. As I understand it, unlike `zsh` native completions, each bash completion must be explicitly required, like you say. So the users could selectively enable them. (Having some details on which ones are zsh-incompatible would help us decide this.) But yeah, if there are significant compatibility concerns, it would be better for us to have a separate "zsh-compatible bash completions" dir, or link them in to site-functions, as a way of indicating zsh compatibility. That would let the user turn them all on, without having to vet them individually, and move responsibility for vetting to the formula maintainers. (If I understand what you're getting at here.) Stuff on `$fpath` does not automatically get hooked in to the completion system unless it is structured like the `_foo` zsh native completion definitions.

2. If you already have a configuration that does `compinit`, it's just a matter of adding one line. Though you still need to decide where to add it: should it come before or after the completions supplied by `zsh` itself? Before or after `zsh-completion`? Or the completions supplied by OMZ or other sources? Ordering concerns aside, a new "known bash-to-zsh-compatible" dir sounds like it would probably be a good idea. 

3. Because of conflicts with completions provided by other packages. The `site-functions` directory is analagous to `#{prefix}/bin`: it is a place for programs and packages to install completion definitions for the commands that they drop in `bin`. There's a close correspondence between them: a package that defines commands `foo` and `bar` may supply `_foo` and `_bar` completions for them, to go in to `site-packages`. Conflicts with other formulae wanting to link `_foo` and `_bar` for their own commands in to `site-packages` is not a concern, because they would already be conflicting due to the commands they want to link in to `bin`, so you're not increasing the incompatibility. However, the `zsh-completion` package supplies completion definitions for a large number of *other* packages' commands. This could end up conflicting with packages which define their own `zsh` completions if both were to go in to `site-functions`. And one conflict would force you to remove `zsh-completions` and lose completions for a bunch of other commands as well.

There aren't many (if any) packages where that conflict actually happens, but because they're independent projects, and the releases are not coordinated, it could happen. And our current testing won't catch it. We could decide that it's Homebrew's responsibility to handle that compatibility, and whenever there's a collision between `zsh-completions` and the package that actually defines the command, choose one of the completions as better, and remove the conflicting one from the formula.

And then there's occasional funky stuff like `hub`, which wants to wrap and alias existing commands from other packages.

If not for the conflicts, then I *think* it would make sense for `zsh-completion` to be symlinked in to `site-functions` instead of its own separate `share` directory: that's a place for globally-available `zsh` functions to go, the way `/usr/local/lib/python2.7/site-packages` is the place for Python bindings to get linked to. And having a single, conventionally-named directory to pull in would make it easier for users to consume.

I am not sure about any of this; I am still learning zsh and its deployment conventions.

**Comment by ELLIOTTCABLE** [comment]
Iiiiiinteresting. Now I understand the `zsh-completions` issue; I'm now thinking it would be a really good idea to add a note about some of this to the post-install on `zsh-completions` (“Due to possible conflicts with individually-installed formula, these are installed to their own directory, `/usr/local/share/zsh-completions`. See <wiki link> for more information on Zsh support.”)

Such a page could then cover some basics, such as `compinit` and manually modifying `$fpath`, and how to enable Homebrew packages in Oh My Zsh, Antigen, Zgen, etceteras.

Sounds like we're on the same page here, now. Let me know if some of this work is something that'd be quick and easy for a newcomer to tackle; I'm happy to contribute. (=

**Comment by apjanke** [comment]
I think we should maybe be conservative about giving advice on these things, because (from what I can tell) the various Zsh configuration layer projects and Zsh itself have not converged on a Right Way to do these things yet. At least in a Homebrew-like world where there might be multiple `zsh` installs on one machine.

This is just my personal opinion, but as a repackager of stable, working software, I think Homebrew should just hang back and see how this shakes out.

**Comment by mikemcquaid** [comment]
> I think we should maybe be conservative about giving advice on these things, because (from what I can tell) the various Zsh configuration layer projects and Zsh itself have not converged on a Right Way to do these things yet. At least in a Homebrew-like world where there might be multiple zsh installs on one machine.

Agreed :+1:

**Comment by MikeMcQuaid** [comment]
We'll accept PRs for this but we're not actively working on it at this time.
