### ISSUE TITLE
Eigen3 not found from Cmake

### ISSUE THREAD

**Issue by jmtatsch** [Homebrew/legacy-homebrew#44937]
Although a CMake Module for discovering Eigen3 is installed into /usr/local/Cellar/eigen/3.2.6/share/cmake/Modules/FindEigen3.cmake
it is not picked up by CMake.

```
cmake --find-package -DCOMPILER_ID=GNU -DLANGUAGE=CXX -DMODE=EXIST -DNAME=Eigen3
Eigen3 not found.
CMake Error: Problem processing arguments. Aborting.

brew info eigen
eigen: stable 3.2.6 (bottled), HEAD
C++ template library for linear algebra
http://eigen.tuxfamily.org/
/usr/local/Cellar/eigen/3.2.6 (367 files, 4,2M) *
  Poured from bottle
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/eigen.rb
==> Dependencies
Build: cmake ✔
==> Options
--universal
    Build a universal binary
--HEAD
    Install HEAD version

brew list eigen
/usr/local/Cellar/eigen/3.2.6/include/eigen3/ (364 files)
/usr/local/Cellar/eigen/3.2.6/lib/pkgconfig/eigen3.pc
/usr/local/Cellar/eigen/3.2.6/share/cmake/Modules/FindEigen3.cmake
```

@wjwwood created a demo repository for this:
https://github.com/wjwwood/eigen_test

**Comment by wjwwood** [comment]
Just to reiterate my comment from the other thread:

I believe the issue comes from the fact that cmake internally references the directory `$(brew --repfix)/Cellar/cmake/<version>/share/cmake/Modules`, but the `eigen` formula adds a file to `$(brew --prefix)/share/cmake/Modules`. This results in the file being present, but not being found by cmake unless you set the `CMAKE_MODULE_PATH` to be `$(brew --prefix)/share/cmake/Modules` explicitly. And if you do that then cmake complains, so I don't think it's a good work around.

I believe that this was not an issue in the past, but I cannot prove that. This leads me to believe it may have been introduced in a recent change to the cmake version or formula.

**Comment by mikemcquaid** [comment]
> I believe the issue comes from the fact that cmake internally references the directory $(brew --repfix)/Cellar/cmake/<version>/share/cmake/Modules, but the eigen formula adds a file to $(brew --prefix)/share/cmake/Modules. This results in the file being present, but not being found by cmake unless you set the CMAKE_MODULE_PATH to be $(brew --prefix)/share/cmake/Modules explicitly. And if you do that then cmake complains, so I don't think it's a good work around.

Seems to me Eigen needs fixed (also possibly upstream) to install to the right location.

**Comment by xu-cheng** [comment]
Actually, I think this is actually from `cmake` which doesn't respect `/usr/local/share/cmake/Modules` as the default search path.

**Comment by mikemcquaid** [comment]
> And if you do that then cmake complains, so I don't think it's a good work around.

It sounds like that's intentional. Given CMake makes syntax changes which aren't backwards compatible it seems to make sense that modules should be version-specific.

**Comment by wjwwood** [comment]
> Seems to me Eigen needs fixed (also possibly upstream) to install to the right location.

To the best of my knowledge `$(brew --prefix)/share/cmake/Modules` is the right location, but cmake is not considering it correctly, but instead is looking to the version of the that folder in its cellar.

> Actually, I think this is actually from cmake which doesn't respect /usr/local/share/cmake/Modules as the default search path.

I agree. It appears to use it's Cellar version of this instead, which imo is not correct.

> It sounds like that's intentional.

I agree, that the warning from cmake is accurate, but that's why I think we need to investigate why cmake doesn't consider this folder by default.

> Given CMake makes syntax changes which aren't backwards compatible it seems to make sense that modules should be version-specific.

I do not believe this is a change in cmake syntax, but rather a problem which occurs with how cmake handles being installed into a folder and then symlinked into place.

**Comment by davetcoleman** [comment]
Hi @wjwwood, great to see you here! I just ran into this FindEigen3 issue to on OSX 10.10 and latest homebrew. Using the old FindEigen.cmake works, though it throws warnings that I shouldn't be using that version. Not sure how to fix this but I thought I'd give my data point.

**Comment by wjwwood** [comment]
@davetcoleman http://wiki.ros.org/jade/Migration#Eigen_CMake_Module_in_cmake_modules

The old `FindEigen.cmake` is something we distributed but are trying to deprecate in favor of the FindEigen3.cmake that Eigen distributes, but we're running into this issue on people who tried. I believe this issue is new and didn't exist when we started the migration, but I could be wrong.

**Comment by davetcoleman** [comment]
Yes, I am using your cmake_modules's version of FindEigen*.cmake

**Comment by traversaro** [comment]
Eigen 3.3 will ship and install a `Eigen3Config.cmake` file [1], so the `FindEigen3.cmake` file should not be needed anymore. This should close this issue, as soon as Eigen 3.3 is released and packaged by homebrew.  

[1] : https://bitbucket.org/eigen/eigen/src/ce5a455b34c0a0ac3545a1497cb4a16c38ed90e8/cmake/Eigen3Config.cmake.in?at=3.3-beta1&fileviewer=file-view-default

**Comment by MikeMcQuaid** [comment]
We'll accept PRs for this but we're not actively working on it at this time.
