### ISSUE TITLE
mongodb fails to find boost headers when installed --with-boost

### ISSUE THREAD

**Issue by mofoyoda** [Homebrew/legacy-homebrew#46505]
I'm sorry, I can't provide logs gist, because installed with internal boost and cleaned up already, but FYI the message was:
```
Checking for C++ header file boost/filesystem/operations.hpp... no
can't find boost headers
```

**Comment by dunn** [comment]
So it's failing during `./configure`?

(If you could try `mongodb --with-boost` again to generate new logs, that'd be great.)

**Comment by DomT4** [comment]
We're probably going to need the logs here to be able to look at the issue, I'm afraid.

**Comment by dunn** [comment]
This configuration is failing for me as well, but I think for a different reason: https://gist.github.com/dunn/58c675230d6455951fe9

Tried with `boost --c++11`, but failed in a similar (but not identical) way: https://gist.github.com/anonymous/79e93cbb1b7ad20f9b17

**Comment by mofoyoda** [comment]
Ok, checked that once again:
```brew install --with-boost --with-openssl --verbose mongodb```
Logs here:
https://gist.github.com/31071c7a745b26d81f18

**Comment by apjanke** [comment]
I can reproduce those "consecutive >>" errors on OS X 10.9.5 with `brew install mongodb --with-boost`. https://gist.github.com/455089a61d95748d3b12

@dunn Those "similar but not identical" failures look to me like the same failure (same error messages at same source code lines) just rearranged due to parallel `make` jobs (`-j4`). Looks like maybe that `boost --c++11` option didn't take effect?

From the formula:
```
  def install
    ENV.cxx11 if MacOS.version < :mavericks
    ENV.libcxx if build.devel?
```

Maybe that `ENV.cxx11` shouldn't be conditional on the OS X version? Or `--with-boost` should also trigger it? I changed it to an unconditional `ENV.cxx11`, and `brew install mongodb --with-boost` succeeded. Logs: https://gist.github.com/410c03b81a18cd0ed623

**Comment by dunn** [comment]
@apjanke Oh, good point!

What I meant by `boost --c++11` was I tried building mongodb against a boost installed with `brew install boost --c++11`.  And since you figured it out that means we don't have to add a non-standard boost dep here.

**Comment by bmike** [comment]
FWIW - 10.11 fails to build as well - Logs: https://gist.github.com/bbdbe7aa8755af6100d0

**Comment by MikeMcQuaid** [comment]
We'll accept PRs for this but we're not actively working on it at this time.
