### ISSUE TITLE
Uninstalling a package with a linked app doesn't remove the link

### ISSUE THREAD

**Issue by grahamc** [Homebrew/legacy-homebrew#46542]
Expected behavior: `brew uninstall emacs` would clean up and remove the app link.

Actual behavior:

```
➜  ~  brew uninstall emacs
Uninstalling /usr/local/Cellar/emacs/24.5... (3923 files, 118M)
```

however `/Applications/emacs.app` still existed.

**Comment by UniqMartin** [comment]
One reason this doesn't happen automatically is because Homebrew tries not to touch stuff outside of its prefix (`/usr/local` by default), unless explicitly asked by the user. Hence, `brew linkapps` is also a separate manual step.

That said, I agree it would be desirable to check if uninstalling a formula breaks any of the symbolic links in `/Applications` and/or `~/Applications` and to notify the user about this (with a suggestion on how to resolve this). Would the following (not currently implemented) work for you?

```
$ brew uninstall emacs
Uninstalling /usr/local/Cellar/emacs/24.5... (3923 files, 118M)

The following linked applications are no longer installed:
  /Applications/emacs.app
Run `brew unlinkapps --uninstalled` to remove these symlinks.
```

**Comment by grahamc** [comment]
Yes, I think that notice would be helpful.

**Comment by DomT4** [comment]
In this case I'd be happy for it to happen automatically on `brew rm`, to be honest. I don't think it's outside our mandate to prune symlinks that we know belong inside our Cellar and no longer exist.

**Comment by UniqMartin** [comment]
Yes, I guess it would be safe to do this automatically. I'll look into implementing this behavior.

**Comment by DomT4** [comment]
You could probably throw out to `brew unlinkapps emacs` (for example) unconditionally in `brew uninstall` as a really simple solution. `brew unlinkapps` doesn't fail hard if an `.app` doesn't actually exist for that package.

Feel free to get elegant as desired though :smile:.

**Comment by MikeMcQuaid** [comment]
We're closing out all issues relating to features that no-one is implementing in the short term in favour of pull requests.
