### ISSUE TITLE
Postgres psql incorrect works on OSX 10.11.2

### ISSUE THREAD

**Issue by 1st** [Homebrew/legacy-homebrew#46860]
Hello.

- Gist: https://gist.github.com/1st/5bbe6da1f5d18c31b419
- OSX 10.11.2

The postgres works well if I connect to it via any external GUI client or via my web application.

Problem appears when I try to connect to postgres via a command line utility:

```shell
$ psql testdb
psql (9.4.5)
Type "help" for help.

Illegal instruction: 4
```

I tried to `brew reinstall postgres` and totally uninstall it and install it again. I even deleted and initialise postgres databases folder `rm -r /usr/local/var/postgres && initdb /usr/local/var/postgres` but nothing help!

I found that this problem may appear when CPP flag pointed to a different version of OSX. Can you check this and repair `psql` tool that comes with `postgres` installation?

Thank you!

**Comment by mikemcquaid** [comment]
Sorry but you have not followed the requested steps on the Troubleshooting page: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting

Please follow (all of) these steps and post the information here so we can help you with your problem.

Thanks!

**Comment by 1st** [comment]
Fixed task description,

**Comment by apjanke** [comment]
What model of Mac is this running on? Might be dependent on the particular CPU you're running. My mid-2010 MacBook Pro with an Arrandale Core i7 CPU was able to run it okay.

**Comment by mikemcquaid** [comment]
> CPP flag pointed to a different version of OSX

Can you elaborate a bit more on what this means? Thanks!

**Comment by 1st** [comment]
@mikemcquaid this mean this answer on [Stack Overflow](http://stackoverflow.com/a/14285922). They told that this problem can appear when used incorrect version in flag `-mmacosx-version-min`.

@apjanke I use Mac mini Late 2012 (Intel Core i5, 2.5 GHz).

**Comment by apjanke** [comment]
I think that Stack Overflow answer might be off a bit. From what I've seen before (and Googling again this time), `Illegal instruction: 4` means an instruction that your CPU, not OS, doesn't support. Compiling against a different OS version might fix it because it might end up compiling different code paths that don't trigger the optimizations that produce that particular instruction, or hit a bug, or whatever.

>  I use Mac mini Late 2012 (Intel Core i5, 2.5 GHz).

Okay. That means you have an [i5-3210M](http://ark.intel.com/products/67355/Intel-Core-i5-3210M-Processor-3M-Cache-up-to-3_10-GHz-rPGA). That's newer than mine, and it is the same family and generation (maybe even the same chip) as the test bot that built the bottle. So I'd bet it's not actually built with unsupported instructions, and this error is being triggered by something else.

I just realized I was still running the 10.11 beta on my 2010 machine. I'll update to 10.11.2 and see if I can reproduce then, though I doubt it.

It's odd that you have no Homebrew logs for `postgresql`. Maybe they were lost in a cleanup since the last install? Could you do a `brew reinstall postgresql` again and see if that gives you logs from the installation? Want to verify that it's pouring from bottle, or building with the default options.

**Comment by MikeMcQuaid** [comment]
If this is still broken: we'll accept PRs for this but we're not actively working on it at this time.
