### ISSUE TITLE
webkitgtk fails to load shared libraries

### ISSUE THREAD

**Issue by WebReflection** [Homebrew/legacy-homebrew#47000]
I'm not sure this depends on [-L/path/to/nonexistent/folder](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/webkitgtk.rb#L40) as flag but when I try to use webkitgtk on OSX El Capitan and gjs I have this error:

```
** (gjs:30127): WARNING **: Failed to load shared library '/tmp/webkitgtk20151207-6932-1shmxi0/webkitgtk-2.10.4/lib/libwebkit2gtk-4.0.37.dylib' referenced by the typelib: dlopen(/tmp/webkitgtk20151207-6932-1shmxi0/webkitgtk-2.10.4/lib/libwebkit2gtk-4.0.37.dylib, 9): image not found

** (gjs:30127): WARNING **: Failed to load shared library '/tmp/webkitgtk20151207-6932-1shmxi0/webkitgtk-2.10.4/lib/libjavascriptcoregtk-4.0.18.dylib' referenced by the typelib: dlopen(/tmp/webkitgtk20151207-6932-1shmxi0/webkitgtk-2.10.4/lib/libjavascriptcoregtk-4.0.18.dylib, 9): image not found

(gjs:30127): Gjs-WARNING **: JS ERROR: Error: Unsupported type void, deriving from fundamental void
``` 

In order to fix this problem I had to `locate libwebkit2` and manually `ln -s /usr/local/Cellar/webkitgtk/2.10.4/lib/ /tmp/webkitgtk20151207-6932-1shmxi0/webkitgtk-2.10.4/lib`so that now everything is fine.

I was going to file a PR but I'm not really familiar with home-brew so I rather let experts figure out, tr tell, what's going on and how to fix this.

Thanks

**Comment by mikemcquaid** [comment]
CC @tschoonj for thoughts here.

**Comment by tschoonj** [comment]
I ran into the exact same problem last week and opened a bug report on the [Webkit bugzilla](https://bugs.webkit.org/show_bug.cgi?id=152183).

Your solution is not something we could put into a Formula though.

**Comment by WebReflection** [comment]
I guess I should close this then. It'd be nice to be updated once the bug has been solved elsewhere. Thanks

**Comment by tschoonj** [comment]
Will take care of that

**Comment by WebReflection** [comment]
apparently in that WebKit bug turned out MacPorts works just fine and it's an Homebrew gotcha, probably Formula related?

**Comment by WebReflection** [comment]
it looks like latest stable `2.10.9` that has just been released should have solved the problem. Can anyone please double check or update the Formula? Thanks!

**Comment by tschoonj** [comment]
Will look into it
On 17 Mar 2016, at 09:00, Andrea Giammarchi <notifications@github.com<mailto:notifications@github.com>> wrote:


it looks like latest stable 2.10.9 that has just been released should have solved the problem. Can anyone please double check or update the Formula? Thanks!

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub<https://github.com/Homebrew/homebrew/issues/47000#issuecomment-197772669>


-- 
This e-mail and any attachments may contain confidential, copyright and or privileged material, and are for the use of the intended addressee only. If you are not the intended addressee or an authorised recipient of the addressee please notify us of receipt by returning the e-mail and do not use, copy, retain, distribute or disclose the information in or attached to the e-mail.
Any opinions expressed within this e-mail are those of the individual and not necessarily of Diamond Light Source Ltd. 
Diamond Light Source Ltd. cannot guarantee that this e-mail or any attachments are free from viruses and we cannot accept liability for any damage which you may sustain as a result of software viruses which may be transmitted in or with the message.
Diamond Light Source Limited (company no. 4375679). Registered in England and Wales with its registered office at Diamond House, Harwell Science and Innovation Campus, Didcot, Oxfordshire, OX11 0DE, United Kingdom

**Comment by tschoonj** [comment]
Opened #50193 to update webkitgtk to 2.10.9 but it does not appear to include the patch for this issue :cry:

**Comment by WebReflection** [comment]
FYI the version 2.12 stable is out (since quite a while) and it should fix the issue.

**Comment by tschoonj** [comment]
I know, but I havent had time to try and build it yet. Feel free to submit a PR yourself.

By the way, I tested 2.11.92 and that had another gobject-introspection issue that resulted in a g-ir-scanner fatal error...

Since I have seen the same issue with glade3, it looks like a gobject-introspection problem. I filed a bug report on gnome bugzilla over it...

**Comment by WebReflection** [comment]
Thanks. PR filed, I wonder if you could link your bug-report here too.

**Comment by tschoonj** [comment]
Sure: https://bugzilla.gnome.org/show_bug.cgi?id=764072

**Comment by WebReflection** [comment]
hey @tschoonj , this has no replies: https://bugzilla.gnome.org/show_bug.cgi?id=764072 and so doesn't this one: https://bugs.webkit.org/show_bug.cgi?id=152183

meanwhile 2.12.2 is out ... is there anything I can do to help?

It looks like webkitgtk via homebrew is a big _nope_ right now, and the current package is kinda broken.

This is also closed: https://github.com/Homebrew/legacy-homebrew/pull/50565

**Comment by tschoonj** [comment]
Well I think it should be possible to build webkitgtk without gobject-introspection support. Can you confirm that this works with the latest release?

**Comment by WebReflection** [comment]
I'm not sure I can, for the simple reason if I drop that I don't think PyGtk or GJS are going to work.

**Comment by tschoonj** [comment]
Not sure what you mean here.

PyGtk has nothing to do with webkitgtk at all. Obviously without gobject-introspection support you won't be able to use webkitgtk in python.

GJS doesn't depend on webkitgtk either. In fact it uses SpiderMonkey as javascript engine instead of JavaScriptCore, which ships with webkitgtk.

There are only three packages in homebrew that have a dependency on webkitgtk:
- `devhelp` uses webkitgtk directly through its C API, so no need for gobject-introspection
- `gnome-build` same here
- `gitg` the 3.18.0 version appears to use webkitgtk through its gobject-introspection bindings , but this is no longer true for 3.20.0, which uses gtksourceview instead of webkitgtk. 

So until Homebrew/homebrew-core#267 is merged in, only `gitg` would break if the webkitgtk gobject-introspection bindings were removed.

**Comment by WebReflection** [comment]
My bad, I should have explained. I've no idea how to use webkitgtk without PyGtk or GJS, both importing it via gobject-introspection.

Since I'm interested in using webkitgtk together with every other working module through gobject-introspection, I hope this can be solved as it is already in MacPorts.

I'll keep waiting. Thanks.

**Comment by tschoonj** [comment]
Ok, now I understand your problem.

Well, if you want to help out here, I suggest you have look at why g-ir-scanner is failing during the gobject-introspection bindings build. Unfortunately no one on bugzilla appears to be doing so 😢 

I cannot do it either as I am not skilled enough in python (also don't have the time)

**Comment by WebReflection** [comment]
will try to have a look in there, cheers

**Comment by WebReflection** [comment]
I know this won't probably help much, but installing webkit2-gtk +quartz via MacPorts takes forever, due lack of prebuilt packages (for some unknown reason they prefer X11 variant) but it works via gir without any sort of problem.

Here how they build it:
https://trac.macports.org/browser/trunk/dports/www/webkit2-gtk/Portfile

**Comment by MikeMcQuaid** [comment]
If this is still broken: we'll accept PRs for this but we're not actively working on it at this time.

**Comment by WebReflection** [comment]
I can confirm it's still broken **and** it takes forever to test a fix. I also gave up, but macports quartz version doesn't have this problem. Sad to see there's not much collaboration between these two projects.

Best Regards
