### ISSUE TITLE
doxygen failed to build on 10.11.2

### ISSUE THREAD

**Issue by bkircher** [Homebrew/legacy-homebrew#48169]
Error when linking executable doxygen.

gist-logs:
https://gist.github.com/569b77ac5f6eda3c3985

**Comment by DomT4** [comment]
It looks like the `with-libclang` option has broken here. It builds from source okay without that activated.

I can't find anything upstream that would indicate it expects to build against LLVM/Clang 3.7.x rather than 3.6.x now but that would seem to be the issue as building against the `llvm37` formula from Homebrew Versions succeeds.

**Comment by MikeMcQuaid** [comment]
If this is still broken: we'll accept PRs for this but we're not actively working on it at this time.
