### ISSUE TITLE
git-prompt.sh is not installed to zsh site-functions

### ISSUE THREAD

**Issue by zmanji** [Homebrew/legacy-homebrew#48428]
From the git formula:

````
    if build.with? "completions"
      # install the completion script first because it is inside "contrib"
      bash_completion.install "contrib/completion/git-completion.bash"
      bash_completion.install "contrib/completion/git-prompt.sh"

      zsh_completion.install "contrib/completion/git-completion.zsh" => "_git"
      cp "#{bash_completion}/git-completion.bash", zsh_completion
    end
````

The `git-prompt` script is installed into the bash completion directory. However from the first line from the script:
````
# bash/zsh git prompt support
````

To make this script useful and accessible for users that use zsh, I think it should also be copied or installed into the zsh site-functions directory.

**Comment by apjanke** [comment]
The zsh `site-functions` directory probably isn't the right place for it; that directory is for autoloaded functions, and this is a normal script that's intended to be sourced. (Same probably goes for `git-completion.bash`, which is currently being copied to `zsh_completion`?)

Seems like `/usr/local/share/git-core/contrib` would be a better place to install it, where users could have their `.zshrc` locate and load it. Or they could just find it in its current location in `#{bash_completion}`, since that's always present on OS X. (Though `#{bash_completion}` seems an odd place for it, too, since it is not a completion definition.)

Those `<file>.install` commands move their targets instead of copying them, so they don't show up in the `/usr/local/share/git-core/contrib` directory upon installation.

**Comment by zmanji** [comment]
Keeping it in `/usr/local/share/git-core/contrib` also sounds like a fine location to me. I just think the current setup is confusing for zsh users.

**Comment by apjanke** [comment]
Yeah, we don't have our `zsh` installation conventions fully sorted out yet. This could be a good opportunity to work on them.

**Comment by MikeMcQuaid** [comment]
If this is still broken: we'll accept PRs for this but we're not actively working on it at this time.
