### ISSUE TITLE
"Installing dependencies for" is truncated to COLUMNS

### ISSUE THREAD

**Issue by sjackman** [Homebrew/legacy-homebrew#48449]
e.g.
```
==> Installing dependencies for roswell/roswell/roswell: xz, homebrew/dup
==> Installing roswell/roswell/roswell dependency: xz
```

I feel that the list of dependencies should not be truncated to the number of columns. The list of packages for the user should not be elided.

The workaround is to install with `-v` or with `COLUMNS=999`.

**Comment by sjackman** [comment]
If the break happens between words by chance, it's impossible to tell that the list has been truncated. A fix for this would be to add an ellipsis `…` at the point of truncation.

**Comment by zmwangx** [comment]
Actually I think it would be better if `oh1` and `ohai` do not truncate at all. Titles printed with `oh1` and `ohai` are usually not so long to begin with, so truncating provides little value and only serves to annoy people when they do want to see the information once in a while.

**Comment by sjackman** [comment]
Just curious, where do the function names `ohai`, `oh1`, `opoo` and `onoe` come from? `ofail` and `odie` are pretty self explanatory.

**Comment by zmwangx** [comment]
Blamed for a few minutes. `ohai` is from https://github.com/Homebrew/homebrew/commit/0b0fa48c313d77b6e4a1d7b472a998b75765437f (Rename h1 to ohai (for the lulz) — which I can't make out). `oh1` https://github.com/Homebrew/homebrew/commit/26a66f80f6738747404bcc38dbedd74d2cac1b25 — I think h1 means `<h1>` i.e. title. `opoo` https://github.com/Homebrew/homebrew/commit/1e08d31e14f78487f4529fffae36d279696fd730#diff-cef16ceb727f1d5a841e0295b083611f — oh, poo? `onoe` https://github.com/Homebrew/homebrew/commit/6b6d3699a29359343725ad0eb1394c46a5c6406b — I'd say it means oh no.

**Comment by UniqMartin** [comment]
FWIW, I also think truncating the output of `ohai` and `oh1` has very little benefit (the output appears slightly cleaner) at the cost of creating confusion. I'd be in support of a PR that eliminated this code [in `ohai`](https://github.com/Homebrew/homebrew/blob/720cdef19ab3ee7f5c89ebebe7c95f0247d74d45/Library/Homebrew/utils.rb#L91) and [in `oh1`](https://github.com/Homebrew/homebrew/blob/720cdef19ab3ee7f5c89ebebe7c95f0247d74d45/Library/Homebrew/utils.rb#L97), but I don't know what the other maintainers' stance on that would be.

**Comment by apjanke** [comment]
I'd personall prefer for them not to be truncated when I use `brew`, especially for the dependencies list. That's caused me some extra work before. But I don't know what most users would prefer. Wish we could do a poll or other survey of them for stuff like this.

Guess it could always be a configuration option.

**Comment by zmwangx** [comment]
I would take a (not so) wild guess and say that most users either don't want truncation or don't care...

**Comment by mikemcquaid** [comment]
I'd rather we not change something like this (that's been the way it is for a long time) without giving it a fair bit of thought on what problems it solves for us.

**Comment by shrx** [comment]
I also think truncation should be at least optional, if not disabled by default.

**Comment by UniqMartin** [comment]
Here's some example output on an 80-column wide terminal (the `|` show the bounds of the terminal):

```
|$ brew install harfbuzz                                                         |
|==> Installing dependencies for harfbuzz: pkg-config, xz, gettext, libffi       |

|$ brew install -v harfbuzz                                                      |
|==> Installing dependencies for harfbuzz: pkg-config, xz, gettext, libffi, glib,|
| libpng, freetype, fontconfig, pixman, cairo, gobject-introspection, icu4c      |
```

The truncated output from the first command shows two issues:

- There's no indication that the output was truncated, so it might be surprising to notice later in the installation process that `libffi` is not the last dependency to be installed before `harfbuzz`.
  - Even if truncation doesn't happen at a word boundary, how many users know that the library is `libffi` and not `libffi-ng` (random example) and thus the output must have been truncated?
- Because truncation doesn't properly handle ANSI escape codes (the dependencies are normally highlighted in green), it actually leaves seven columns unused.

My personal conclusion would be that truncation has no advantages and several disadvantages:

- Added complexity.
  - Even more so to get truncation right in the presence of ANSI escape codes.
  - Even more so if we want to make truncation clearer by appending something like `…`.
- Potential for confusing more advanced users.
- Most other users probably don't pay attention to this and similar lines, thus don't care how neat the output looks like (I'm presuming neat output is the primary goal of the truncation).

*Some trivia:* Truncation was introduced in d40718f4de90e527897f91061ecded86b6c93699, a commit that deals with an unrelated issue and doesn't even use `ohai`. It was basically there from the very beginning of the project (2009), was refactored multiple times, but was never really changed.

**Comment by mikemcquaid** [comment]
The reason for truncation is implied from the original name `oh1`. This is a header row describing output that's to come rather than a complete list.

With stuff like this I'm pretty :-1: on changing it unless we can point to actual user issues that would be resolved by changing it. I don't like adjusting stuff like this that's been the same for a long time unless we're totally sure it's necessary.

**Comment by mikemcquaid** [comment]
On the flip side, any replacement for this should be formatted similarly and would need to do smart output to insert newlines so they don't just come in the middle of words. Even then I suspect we'll annoy some people with the change.

**Comment by sjackman** [comment]
Perhaps remove the packages from the header line, and print the word-wrapped package names after the header line. e.g.
```
brew install harfbuzz
==> Installing dependencies for harfbuzz
    pkg-config, xz, gettext, libffi, glib, libpng, freetype, fontconfig, pixman,
    cairo, gobject-introspection, icu4c
```

**Comment by zmwangx** [comment]
> I don't like adjusting stuff like this that's been the same for a long time unless we're totally sure it's necessary.

That's a very reasonable attitude, but I think truncation really violates the principle of least surprise. A very basic expectation for any textual interface is that long lines either wrap or scroll, so that no information is lost. Most terminal emulators are not horizontally scrollable (unless you use something like curses to provide scrolling on top of terminals, but TUI is a different story), so long lines should wrap, naturally. Truncation without scrollability is just lossy and confusing (even more so when you truncate at the wrong place; see Martin's example). Indeed, I can hardly think of any well-known utility that truncates to terminal width — only `ps` comes to mind, but that's an entirely different use case, where `ps` is displaying a table of sort, and not truncating could potentially create a huge unreadable mess (not that I like or endorse truncation there).

**Comment by MikeMcQuaid** [comment]
Closing old usability issues in favour of pull requests.
