### ISSUE TITLE
zsh completions for `brew` broken by zsh-completions 0.14 upgrade

### ISSUE THREAD

**Issue by bkircher** [Homebrew/legacy-homebrew#49066]
zsh completions do not work anymore with latest zsh-completions formula. Reverting d41a8a9d4c66b3654e2a26a90a3c00f9a4a2c3d7 and re-installing 0.12 resolves the issue.

**Comment by UniqMartin** [comment]
Have you checked with upstream whether that is a known issue or whether there might be a problem with your configuration? My guess is that this is unlikely to be an issue that is specific to Homebrew.

**Comment by bkircher** [comment]
Nope, not really. Sorry. Upstream issue tracker however shows nothing
https://github.com/zsh-users/zsh-completions/issues
We're investigating on IRC right now.
Should I file upstream?

**Comment by UniqMartin** [comment]
> Should I file upstream?

Yes, please. And if you come to some conclusion that requires action on our side at Homebrew, please let us know (preferably with a link to the upstream issue/discussion). Thanks!

**Comment by ilovezfs** [comment]
@UniqMartin Perhaps the non-upstream bug here is that the test in the formula should have caught this but didn't.

**Comment by ilovezfs** [comment]
@UniqMartin @bkircher Ah, I found the problem.

https://github.com/zsh-users/zsh-completions/issues/305
https://github.com/zsh-users/zsh-completions/issues/305#event-539887925

So the zsh-completions formula needs to specifically link in the brew completions from `Library/Contributions/brew_zsh_completion.zsh`

```
cd /usr/local/share/zsh-completions
ln -s ../../Library/Contributions/brew_zsh_completion.zsh _brew
```

with

```
fpath=(/usr/local/share/zsh-completions $fpath)
autoload -U compinit
compinit
```

in .zshrc resolves the problem.

**Comment by UniqMartin** [comment]
@ilovezfs Thanks for the investigation! Not sure if that is the issue the original poster is facing, as the claim in the top comment is that `zsh-completion` is broken, not completion for the `brew` command when using `zsh` as a shell as far as I understand it. (But with the little information that is provided in the top comment, we don't know yet what exactly is broken and under which circumstances.)

**Comment by ilovezfs** [comment]
@UniqMartin I experienced the same breakage until I added

```
fpath=(/usr/local/share/zsh-completions $fpath)
autoload -U compinit
compinit
```

not just

```
fpath=(/usr/local/share/zsh-completions $fpath)
```

to my profile.

**Comment by UniqMartin** [comment]
@ilovezfs Not being a `zsh` user I assumed it was implied to add these two lines (`autoload -U compinit` and `compinit`) to one's `.zshrc`. I did when I tested the completion for `brew` with `zsh` and I did it because the ZSH manual told me to. I wasn't aware that things could have previously worked without those two lines or that they were at all related to the update of `zsh-completions` from 0.12 to 0.14.

From the information I have so far, I'm not sure if there is something actionable on the Homebrew side. What is your opinion (as a `zsh` user and nowadays also frequent contributor)? :smile_cat:

I think we should also give the original poster a chance to explain what the issue they ran into is and if they were able resolve it by now. (Us speculating and acting blindly is not necessarily helpful here.)

**Comment by ilovezfs** [comment]
I'm not a zsh user either. I got the idea for those two lines from the test case, which does that even though the caveats don't say to. I don't know whether it's supposed to work without them or not, but if they're supposed to be required the caveat should be updated to reflect that. It seemed to have worked a couple times before without them but I think there may be some odd interaction going on with whether the homebrew zsh is installed too that causes intermittent success/failure without them.

As for the original poster, I am cheating. He was in the IRC channel earlier troubleshooting this with me before he filed the bug report. I told him you were going to say to file a bug report upstream :)

I just mentioned the two changes I made to get it to work, so hopefully he'll report back whether that fixes it.

**Comment by UniqMartin** [comment]
> I don't know whether it's supposed to work without them or not, but if they're supposed to be required the caveat should be updated to reflect that.

No. If there is something Homebrew-specific like the installation location, that has to go into the caveats. But the caveats are not a replacement for upstream documentation which is the right (and only) place for information on how to work with a specific piece of software, e.g. for how to enable completions in `zsh`. Putting that into the caveats is prone to quickly become inaccurate and outdated.

> As for the original poster, I am cheating. He was in the IRC channel earlier troubleshooting this with me before he filed the bug report. I told him you were going to say to file a bug report upstream :)

Alright, that explains things and why you chimed in. :smile_cat:

**Comment by ilovezfs** [comment]
@UniqMartin the caveats *already* say
```
To activate these completions, add the following to your .zshrc:

  fpath=(/usr/local/share/zsh-completions $fpath)

```
If the other two lines are needed to, I'm suggesting they be added to that preexisting (incomplete?) instruction.

**Comment by bkircher** [comment]
Hi there! Thanks for all the investigation. I'll try as soon as I have some time (and create a PR if successful).

**Comment by lanox** [comment]
I seem to be having same problem after upgrading to zsh-completions: stable 0.14.0,.

@UniqMartin i have that in my zshrc but no louck.  

it seems like _brew has been removed.

**Comment by ilovezfs** [comment]
@lanox Other than the _brew issue, did the upgrade to 0.14.0 break anything else for you?

**Comment by lanox** [comment]
@ilovezfs only upgrade it about 7 hours ago, at the moment I can only see this issues.

**Comment by lanox** [comment]
Although i did notice that zsh-completion for brew is little different to what it was ??

```
❯ brew
audit          -- check formulae for Homebrew coding style
cat            -- display formula file for a formula
cleanup        -- uninstall unused and old versions of packages
commands       -- show a list of commands
config         -- show homebrew and system configuration
create         -- create a new formula
deps           -- list dependencies and dependants of a formula
desc           -- display a description of a formula
doctor         -- audits your installation for common issues
edit           -- edit a formula
fetch          -- download formula resources to the cache
gist-logs      -- generate a gist of the full build logs
home           -- visit the homepage of a formula or the brew project
info           -- information about a formula
install        -- install a formula
leaves         -- show installed formulae that are not dependencies of another installed formula
link           -- link a formula
linkapps       -- symlink .app bundles provided by formulae into /Applications
list           -- list files in a formula or not-installed formulae
log            -- git commit log for a formula
migrate        -- migrate renamed formula to new name
missing        -- check all installed formuale for missing dependencies.
outdated       -- list formulae for which a newer version is available
pin            -- pin specified formulae
postinstall    -- perform post_install for a given formula
prune          -- remove dead links
reinstall      -- install a formula anew; re-using its current options
remove         -- remove a formula
search         -- search for a formula (/regex/ or string)
switch         -- switch between different versions of a formula
tap            -- tap a new formula repository from GitHub, or list existing taps
tap-info       -- information about a tap
tap-pin        -- pin a tap
tap-unpin      -- unpin a tap
test-bot       -- test a formula and build a bottle
uninstall      -- uninstall a formula
unlink         -- unlink a formula
unlinkapps     -- remove symlinked .app bundles provided by formulae from /Applications
unpin          -- unpin specified formulae
untap          -- remove a tapped repository
update         -- fetch latest version of Homebrew and all formulae
upgrade        -- upgrade outdated formulae
uses           -- show formulae which depend on a formula
--cache        bottle         desc           homepage       ls             readall        tap-pin        untap
--cellar       bundle-dir     diy            info           man            reinstall      tap-readme     up
--config       bundle-old     doctor         instal         migrate        remove         tap-unpin      update
--env          cat            dr             install        missing        rm             test           update-bash
--prefix       cleanup        edit           irb            options        search         test-bot       update-report
--repo         command        environment    leaves         outdated       server         tests          upgrade
--repository   commands       fetch          link           pin            sh             uninstall      uses
-S             config         gist-logs      linkapps       postinstall    style          unlink         versions
abv            configure      graph          list           profile        switch         unlinkapps     which
audit          create         help           ln             prune          tap            unpack
beer           deps           home           log            pull           tap-info       unpin
```

I don't recall seen anything after ```uses           -- show formulae which depend on a formula```

**Comment by ilovezfs** [comment]
@lanox Here's what's changed: https://gist.github.com/ilovezfs/fc794108cf0462d9b8b4

If you want the old file back, it's here:
https://github.com/zsh-users/zsh-completions/blob/e6354e099ed31970afdecb7814db653b591848af/src/_brew

**Comment by UniqMartin** [comment]
`zsh-completions` previously shipped its own version of completions for `brew`. Those were dropped in favor of the official completions maintained by Homebrew. A certain difference in behavior and the need to make those official completions known to `zsh` is thus inevitable.

I'm not a `zsh` user, so take my advice with a grain of salt. If I'm understanding things correctly, the “right way” to activate completion for `brew` under `zsh` is to symlink `$(brew --prefix)/Library/Contributions/brew_zsh_completion.zsh` to `$(brew --prefix)/share/zsh/site-functions/_brew` as described in the [Tips & Tricks](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Tips-N'-Tricks.md#command-tab-completion) document. This is the same directory where other formulae like `youtube-dl`, `ninja`, or `hub` install their completions. Then, add the following to `.zshrc`:

```
fpath=($(brew --prefix)/share/zsh/site-functions $fpath)
```

The above procedure is completely independent of what `zsh-completions` offers, i.e. one can have the above without `zsh-completions` and vice versa. (But the `_brew` symlink certainly doesn't belong in the `zsh-completions` directory as suggested further up.) To then make `zsh-completions` known to `zsh`, one has (as suggested in the formula caveats) to add the following to `.zshrc`:

```
fpath=($(brew --prefix)/share/zsh-completions $fpath)
```

I hope I haven't caused even more confusion …

**Comment by ilovezfs** [comment]
@UniqMartin https://github.com/Homebrew/homebrew/blob/master/Library/Formula/bash-completion.rb#L36-L38

zsh-completions.rb needs the equivalent stanza now.

**Comment by UniqMartin** [comment]
> @UniqMartin the caveats already say
>
> ```
> To activate these completions, add the following to your .zshrc:
>
>   fpath=(/usr/local/share/zsh-completions $fpath)
> ```
>
> If the other two lines are needed too, I'm suggesting they be added to that preexisting (incomplete?) instruction.

The caveats say “to activate **these** completions”, not completions in general. So assuming the user has already enabled completions in their `.zshrc` (they don't need to install `zsh-completions` for that), the instructions explain how to *add* the newly installed completions to the already enabled/configured ones.

(I realize the difference is subtle, but I hope I managed to make the difference clear without causing even more confusion.)

> @UniqMartin https://github.com/Homebrew/homebrew/blob/master/Library/Formula/bash-completion.rb#L36-L38
> 
> zsh-completions.rb needs the equivalent stanza now.

I understand how you came to this conclusion, but I don't think it is correct. (Ideally, I'd like to see a comment by an actual experienced `zsh` user on this matter.)

In the `bash` world things are simple and there's only `bash-completion`, so if there is a formula that should “host” `brew`'s official completion that would be it. In `zsh` land things are a bit more difficult, various concurrent systems exist for (elaborately) configuring the shell, and not everyone uses `zsh-completions`.

> Interestingly this reveals a "bug" with the bash-completion formula and bottle, namely that it should have received a revision bump as part of 23027e71ef539df3499eb67053d083d0c326e909 (#48188)

I posted the response to this over at https://github.com/Homebrew/homebrew/pull/48188#issuecomment-183117822 to avoid further conflating these otherwise unrelated issues.

**Comment by ilovezfs** [comment]
>The caveats say “to activate these completions”, not completions in general. So assuming the user has already enabled completions in their .zshrc (they don't need to install zsh-completions for that), the instructions explain how to add the newly installed completions to the already enabled/configured ones.

The caveats' instructions in bash-completion.rb are necessary and sufficient to make the completions work. The caveats' instructions in zsh-completions.rb are necessary but not sufficient to make the completions work. That inconsistency is not explained away by getting into the semantics of "the" vs. "these," but if you'd like to (http://dictionary.reference.com/browse/this?s=t), you're assuming definition (1) isn't a legitimate interpretation of the sentence, but unfortunately it is. Yes, definitions (2) and (3) are there as well, but that doesn't make definition (1) disappear.

**Comment by UniqMartin** [comment]
I guess we simply disagree on what the caveats should contain. Before I give up, I'll try one last time to (convincingly?) summarize what I think characterizes good caveats:

- They are there to convey Homebrew-specific information (like specific paths) that cannot be readily inferred from the upstream documentation.
- They are no substitute for the upstream documentation and thus don't need to be sufficient.

**Comment by ilovezfs** [comment]
And I'll just quote from the IRC channel:

>1:39 PM <ngoldbaum> ilovezfs_: i am a zsh user, if i was new to it adding those two lines would definitely be non-obvious

**Comment by lanox** [comment]
I am at work currently, I will read through all the comments, since I been using zsh for years now and see if I can contribute.

**Comment by lanox** [comment]
@UniqMartin reading the conversation between yourself and @ilovezfs i tend to agree with @ilovezfs. I have been using zsh for few years now and I had no idea that i have to add  ```$(brew --prefix)``` to fpath.

I believe that  we should be told to modify ```fpath``` if any changes have been made or autocompletions have been read from elsewhere as well.

I also can see where you coming from with this comment
 ```To activate these completions, add the following to your .zshrc:

  fpath=(/usr/local/share/zsh-completions $fpath)``` as that is specific for zsh-completions.

But as i said before i had no idea that _brew has been removed from zsh-completions in favour of one that comes with brew and especially located at different location.

I hope this makes sense.

**Comment by ilovezfs** [comment]
@lanox thanks for your perspective. @UniqMartin is fine with caveats mentioning the fpath needed, which they already do:

https://github.com/Homebrew/homebrew/blob/51d5af08e29e7893b6978585a50664495b7c0d52/Library/Formula/zsh-completions.rb#L19

He also is fine with fixing the _brew specific issue in a way that doesn't require intervention, and he's already put together a nice pull request to take care of that for everyone:
https://github.com/Homebrew/homebrew/pull/49099

The only thing we are disagreeing about is whether *in addition* to the preexisting caveat about about the fpath, whether that caveat should *also* include an instruction that the user should add to .zshrc these two lines as well:

```
autoload -U compinit
compinit
```

Do you know if those two lines are even supposed to be necessary? The documentation here seems to imply they're needed if you use `oh-my-zsh` but doesn't say anything about adding them if you don't use `oh-my-zsh`. 

https://github.com/zsh-users/zsh-completions

However, elsewhere on the web, some guides say to always add them, and the brew test case does add them. I couldn't seem to get it to work without them, so I don't know if that's a bug or just an upstream documentation issue. If they are indeed always required, I was suggesting the brew caveats should say that.

Do you know if they're supposed to be needed even when you don't use `oh-my-zsh`? If not, any idea why I seemed to have to add them for it to work?

**Comment by lanox** [comment]
@ilovezfs, ah i see... sorry i was reading it quickly.

Yes that is required if you want to use autocompletion. So that i don't explain it wrongly you could have a look at this .

```man zshbuiltins``` and search for autoload 
also http://zsh.sourceforge.net/Doc/Release/Completion-System.html#Autoloaded-files

look at 20.2 and 20.2.1

**Comment by ilovezfs** [comment]
@lanox Thank you. That's very helpful. Can you think of any circumstance where the completions would work without compinit?

@bkircher did you get all the completions (including the non-_brew ones) working? Did you already have those lines in your .zshrc when you were seeing the breakage?

**Comment by lanox** [comment]
@ilovezfs not that I am aware of , I think you need to have 
```
autoload -U compinit
compinit
```
This will define a few utility functions, arrange for all the necessary shell functions to be autoloaded, and will then re-define all widgets that do completion to use the new system. So i don't think that zsh completion would work at all with out those lines.

**Comment by apjanke** [comment]
Zsh user here.

```
autoload -U compinit
compinit
```

Those two statements are the normal way of initializing Zsh's modern* completion system, and need to happen at some point during `zsh`'s startup (if you want to use completion). Typically they are in `~/.zshrc`. But they can also be run by other code called by `~/.zshrc`. E.g. if you run Oh My Zsh, then Oh My Zsh calls it for you during its initialization. Or on some systems (including some Linux distros), the system-level `/etc/z*` config files do it.

This is basic zsh setup. Most existing `zsh` users will already be doing this one way or another, but they may not know how or where. (If you just run `zsh` for the first time, it will walk you through a wizard which can put this in your `~/.zshrc` for you.)

> Do you know if those two lines are even supposed to be necessary? The documentation here seems to imply they're needed if you use oh-my-zsh but doesn't say anything about adding them if you don't use oh-my-zsh:
>
> https://github.com/zsh-users/zsh-completions

This bit about adding them if you run OMZ is about working around a specific bug in the interaction between OMZ and `zsh-completions` *when installed as an OMZ plugin*. OMZ does that `compinit` for you , and plugins are added to `$fpath` when they're loaded. But autoloaded completions are picked up from `$fpath` at the time of `compinit`, which happens *before* plugins are loaded, so doesn't see `zsh-completions`, so you have to explicitly re-run `compinit` after OMZ initialization. There's an open bug in OMZ with details: robbyrussell/oh-my-zsh#4614.

We probably shouldn't include an instruction to just add those lines to `~/.zshrc`. It's not Homebrew-specific. It won't be necessary for most users, and for many, it would be the wrong thing to do, even if they don't already have those lines in `~/.zshrc` itself, because it could result in running `compinit` twice, possibly with different options and `$fpath` states and with intervening completion setup, which you don't want to do, for performance reasons if nothing else. Might be better to just include a link to the completion sections in the Zsh [Reference Manual](http://zsh.sourceforge.net/Doc/Release/Completion-System.html#Initialization) or [User's Guide](http://zsh.sourceforge.net/Guide/zshguide06.html#l152). Nothing about it is Homebrew-specific ( aside from `/usr/local/share/zsh/site-completions` not being on `$fpath` *for the system-provided `zsh` in `/usr/bin`*).

The brew test case adds them because it runs in a sandboxed home dir with an empty `~/.zshrc`, so it sets up a well-known minimal `.zshrc` that initializes completion. (And it's not adding to an existing `.zshrc`; it's writing the entire file there.)

The `zsh-completions` case is also a bit different from the Homebrew-provided `_brew` completion because it installs to a path which is never on `$fpath` by default. For the Homebrew-supplied `_brew` completion, if you link that in to `$(brew --prefix)/share/zsh/site-functions`, that will be on the default `$fpath` for brewed `zsh`, but not for the system `zsh`. Other `zsh` installations may or may not have it on `$fpath` by default, depending on where `brew --prefix` is and how they were built.

The unique location of the installed completions for `zsh-completions` is the only Homebrew-specific stuff that makes caveats necessary. Even the rest of the `zsh-completions` caveats are general troubleshooting advice for `zsh` completion, and IMHO could be removed.

*(There's also an older zsh completion system, called "compdef" to distinguish it from the modern "compinit" system.)

**Comment by apjanke** [comment]
@lanox

> I have been using zsh for few years now and I had no idea that i have to add $(brew --prefix) to fpath.

Yeah, we need to do a better job informing `zsh` users about this, and how to configure `zsh` to work with Homebrew-installed stuff. It probably deserves a whole section in the Homebrew setup documentation. Maybe with a link to it in the output of the initial Homebrew installation script if it detects that you are running `zsh`.

**Comment by ilovezfs** [comment]
@apjanke Thank you, that was super helpful. Given that _brew used to be distributed by upstream zsh-completions and now has been yanked due to their rule that "completions are not accepted when already available in their original project" and the existence of <url>https://github.com/Homebrew/homebrew/blob/master/Library/Contributions/brew_zsh_completion.zsh</url> , how would you suggest that the situation be addressed in a zsh-sane way since users just had their brew completions "disappear"?

For users who use exclusively brewed zsh,
```
ln -s  ../../../Library/Contributions/brew_zsh_completion.zsh $(brew --prefix)/share/zsh/site-functions/_brew
```
will get it working again.

For users who use /bin/zsh or both /bin/zsh, brewed zsh, or both

```
ln -s  ../../../Library/Contributions/brew_zsh_completion.zsh $(brew --prefix)/share/zsh/site-functions/_brew
```
*and* adding `fpath=($(brew --prefix)/share/zsh/site-functions $fpath)` to .zshrc will get it working again.

Should there be a new caveat added to zsh-completions about the `fpath=($(brew --prefix)/share/zsh/site-functions $fpath)` step?

Should zsh-completions do `ln -s  ../../../Library/Contributions/brew_zsh_completion.zsh $(brew --prefix)/share/zsh/site-functions/_brew` as a post install step? Should it instead put the link with the other zsh-completions even though technically it can be used without them? Is it harmful if it's linked in both spots simultaneously?

Should it do neither and instead have a caveat saying what happened and just link to <url>https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Tips-N'-Tricks.md#command-tab-completion</url> ?

Should it just remain silent on the matter and expect users to find this issue or the Tips-N'-Tricks on their own?

**Comment by UniqMartin** [comment]
@apjanke Thank you for the detailed comment, particularly for phrasing some of the stuff I tried to express better than I ever could and for including additional information on the `zsh` completion system and the differences between a brewed and system `zsh`! I've learned something today. :smile_cat:

**Comment by bkircher** [comment]
Doing 

```sh
$ sudo ln -s /usr/local/Library/Contributions/brew_zsh_completion.zsh \
    $(brew --prefix)/share/zsh/site-functions/_brew
```

as @ilovezfs suggests, resolves this issue for me. Hombrew completions are back.

For the sake of completeness, here are the relevant parts in my `~/.zshrc`. I use Oh My Zsh:
```sh
plugins=(git node) # Note: no zsh-completions plugin here
source $ZSH/oh-my-zsh.sh

# ... snip ...

fpath=($(brew --prefix)/share/zsh-completions $fpath)
autoload -Uz compinit
compinit
```
I guess, only issue left is determining whether this should be in zsh-completions' Caveats section or done in a formula, right?

**Comment by apjanke** [comment]
You're welcome!

> how would you suggest that the situation be addressed in a zsh-sane way since users just had their brew-specific completions "disappear"?

I'd say add a caveat to the `zsh-completions` formula along the lines of "zsh-completions no longer provides completion for `brew` itself. See \<that Tips-n-Tricks section\>", and maybe add a specific section to Tips-n-Tricks about this `zsh-completion` 0.14 migration and how to address that. Describing remediation for everybody in the caveat would make it awful long. Especially since eventually the migration will have been well in the past. And we might end up having to change that a few times, which works better in documentation than in a formula definition.

And renaming this issue to something like "zsh completions for `brew` broken by zsh-completions 0.14 upgrade" to make it easier to find for other users having the same problem.

This is a bit of a rough transition, since `brew` completion for zsh doesn't work out of the box, and we haven't yet figured out the right way to install it and instruct users to configure it. Sorry about that.

The best approach for most users would probably be to add that symlink (`ln -s $(brew --prefix)/Library/Contributions/brew_zsh_completion.zsh $(brew --prefix)/share/zsh/site-functions/_brew`), and conditionally add `$(brew --prefix)/share/zsh/site-functions` to their `$fpath` in `~/.zshrc` if it's not already there. I think that would be unlikely to break whatever the official setup method ends up being.

**Comment by ilovezfs** [comment]
@bkircher I'm glad you got it working again. A separate formula just for brew completions is an interesting idea especially if it could be done in such a way that both install and uninstall worked as expected. But yeah the general question is how to address this for everyone that just lost their _brew completions and has no idea why or what to do about it.

**Comment by bkircher** [comment]
> And renaming this issue to something like "zsh completions for brew broken by zsh-completions 0.14 upgrade" to make it easier to find for other users having the same problem.

Done

**Comment by apjanke** [comment]
@bkircher Try doing this in your `~/.zshrc` instead.

```
plugins=(git node) # Note: no zsh-completions plugin here
fpath=($(brew --prefix)/share/zsh-completions $fpath)
source $ZSH/oh-my-zsh.sh

# removed call to compinit
```

That will avoid double-calling `compinit`, and could improve your startup times a bit, or at least make for a cleaner `~/.zshrc`. Could also avoid weird interactions with plugins that do hacky things with the completion internals and make things easier to debug if you ever encounter that.

**Comment by ilovezfs** [comment]
@apjanke what do you think about the idea for a separate formula? There's precedent in that the bash-completion formula installs a similar symlink.

**Comment by bkircher** [comment]
@apjanke 
> Try doing this in your ~/.zshrc instead.
\<snip/>
That will avoid double-calling compinit, and could improve your startup times a bit, or at least make for a cleaner ~/.zshrc. Could also avoid weird interactions with plugins that do hacky things with the completion internals and make things easier to debug if you ever encounter that.

Done and works as expected. Thanks

**Comment by apjanke** [comment]
> what do you think about the idea for a separate formula? There's precedent in that the bash-completion formula installs a similar symlink.

I dunno.

The way `bash-completion` installs a symlink to a Homebrew-provided file is an odd thing for a formula to do. That's not a file supplied as part of the project the formula is for, and doing that symlink is (I think) not part of upstream's normal installation process. Sounds like a hack leftover from early Homebrew days.

I'd rather go the other way, and have completions supplied by Homebrew be installed and work out of the box, with as little user configuration as possible. i.e. check these two symlinks in to the core `homebrew` repo so they're there by default for everyone.

```
etc/bash_completion.d/brew_bash_completion.sh -> Library/Contributions/brew_bash_completion.sh
share/zsh/site-functions/_brew -> Library/Contributions/brew_zsh_completions.zsh
```

Then for `zsh` users, all you have to do is get `/usr/local/share/zsh/site-functions` on your `$fpath` (if you're using the system `zsh`) and you're good to go.

Only major concern there would be conflicts with formulae which themselves want to link or install those files. Could be dealt with on a per-formula basis. It's a little unclean from an architecture perspective. But it doesn't seem any worse than unconditionally installing a `brew` command directly in to `bin/`.

**Comment by ilovezfs** [comment]
```
Then for zsh users, all you have to do is get /usr/local/share/zsh/site-functions on your $fpath (if you're using the system zsh) and you're good to go.
```
I wonder if brew could also provide a runcom snippet that tests which zsh is in play and conditionally sets fpath accordingly. Then just direct users to source that.

**Comment by apjanke** [comment]
What do you mean by a "runcom snippet"?

**Comment by ilovezfs** [comment]
a piece of a .zshrc profile

**Comment by apjanke** [comment]
The decision whether to pull in the `/usr/local` or brewed `zsh-completions` to the system is a human one; `brew` can't know based on which `zsh` is running. And once you make that decision, it's basically just adding `fpath=($(brew --prefix)/share/zsh-completions $fpath)`. Anything more complicated than that would be specific to the user and how they wanted their `.zshrc` to work.

If you mean as output from `brew`, you probably want to avoid doing that. `brew` takes about 10-15 msec to launch, so you want to avoid doing that in shell startup unless there really were run-time decisions to be made.

**Comment by ilovezfs** [comment]
>Anything more complicated than that would be specific to the user and how they wanted their .zshrc to work.

Fair enough.

So is there some case against always installing the symlinks for everyone that we're overlooking?

**Comment by lanox** [comment]
After reading all this, in my opinion we should just notify the user of what they have to do or point the to right documentation/this page. Anything else is complicating .

**Comment by ilovezfs** [comment]
I'm thinking we should just install a symlink to the in-tree brew_zsh_completion.zsh as part of installing zsh-completions.rb. If someone wants to only install brew_zsh_completion.rb,  and not install zsh-completions.rb, then that can be an advanced configuration that they manage themselves with the site-functions, etc.

_brew was always part of zsh-completions.rb, and I see no user-centric reason to change that just because upstream made a decision to yank their file due to the existence of the Homebrew-project-provided file.

**Comment by superlukas** [comment]
I basically agree with @UniqMartin. If you're familiar with zsh all of the things mentioned here should be fairly obvious (if not, they're explained in the documentation.)

One possible change would be to move (or symlink) brew_zsh_completion.zsh to prefix/share/zsh/site-functions, which means that zsh users who chose /usr/local as their prefix don't have to do anything (at least since zsh 5.0.7, which added /usr/local/share/zsh/site-functions to the default $FPATH). OS X currently ships zsh 5.0.8 IIRC. People who chose a different prefix should be aware of the implications. All of this applies to the bash completion as well (I think).

**Comment by apjanke** [comment]
> One possible change would be to move (or symlink) brew_zsh_completion.zsh to prefix/share/zsh/site-functions

I'd probably be in favor of this. Seems like the quickest and simplest fix. But I think we should think it through fully before pushing a change, to avoid flip-flopping on configuration if it turns out there's a better way to do it.

Probably best as a symlink (in either direction) instead of moving. We should keep the old `brew_zsh_completion.zsh` file in place, so that users who've linked to it from other locations don't get their completions broken in the change.

> OS X currently ships zsh 5.0.8 IIRC

Yeah, 10.11 El Capitan ships `zsh` 5.0.8, and introduced `/usr/local/.../site-functions` being on the system `/bin/zsh`'s `$fpath` by default.

> All of this applies to the bash completion as well (I think).

Not quite, I think. As I understand it, the `bash_completion.d` convention and how completions are loaded from there is entirely from the `bash-completions` and user configuration layer, and not a feature of base `bash`. Whereas `site-functions`, `$fpath`, and their interaction with `compinit` is part of base `zsh`. Detection of `bash_completion.d` relies purely on config files, for any bash version or compilation options. (I think.)

The upshot of this is that bash completion setup will not be sensitive to `bash` version differences the way the `zsh` completion stuff is.

**Comment by superlukas** [comment]
I agree completely. Would it still be useful to symlink the bash compl script in the same fashion? (I.e., to prefix/etc/bash_completion.d)

**Comment by apjanke** [comment]
Yes, imho. Makes sense to do all mainstream shells that Homebrew supports in this way.

Right now, the `bash-completion` formula does that symlinking of the Homebrew-supplied bash completion file. I think it's a historical quirk that it's done by that formula, and would make more sense to be done by the same core mechanism that would symlink the zsh completion stuff too.

Just checking in symlinks for both of them to the main Homebrew repo and saying "okay, everybody's got them now" seems like a pretty good approach to me. But I don't want to go off half-cocked on this, because it's touching on design questions for a) how does Homebrew deploy/install pieces of its own functionality, and b) how do zsh extensions get deployed.

Coming at it the other way, does anyone know specific reasons to *not* symlink these completion definitions in for all Homebrew users as part of the core Homebrew distribution?

**Comment by apjanke** [comment]
> I'm thinking we should just install a symlink to the in-tree brew_zsh_completion.zsh as part of installing zsh-completions.rb.

This doesn't really make sense to me. Formulae are ways of installing third party software. The `zsh-completions` formula isn't an area of functionality related to zsh completions; it's a specific package name `zsh-completions`. If that package isn't providing a file/function, Homebrew shouldn't just be sticking it in as part of the formula.

**Comment by ilovezfs** [comment]
@apjanke That's fine. It would certainly make more sense if brew had meta packages, and that was one of them. I'm just thinking of the users who had _brew one day, and then don't have it the next, who really should be sent on as limited an expedition as possible to get back to what they had the day before.

**Comment by apjanke** [comment]
> I'm just thinking of the users who had _brew one day, and then don't have it the next, who really should be sent on as limited an expedition as possible to get back to what they had the day before.

I hear you. Might be worth also mentioning it to the `zsh-completions` maintainers who yanked it without giving a heads-up to Homebrew or supplying a migration path. If we had known about this ahead of time, it would have been easier to come up with a smooth transition mechanism.

In fact, maybe `zsh-completions` could add in a transitional shim that just locates the Homebrew-supplied completions and loads those in, so that their users have a smooth migration experience. And I intentionally say "their users" here: this is a set of completions for the `brew` command, but it's a feature supplied by a third-party project, not Homebrew, and a breaking behavior change in a third-party project, not Homebrew. It would be quicker to pull in a formula update with a compatibility shim than it would be to make a change in core Homebrew.

I'm thinking a mention in caveats and a section in the doco is probably the best we can do for `zsh-completions` users per se. We do formula customizations to get them to install on Homebrew or OS X and play well with other formulae, but not to extend functionality. And Homebrew has a pretty static view of formulae, so adding version transition and back-compatibility stuff is hard. We generally leave that up to the upstream developers of projects that formulae install.

**Comment by ilovezfs** [comment]
@apjanke It is certainly a problem of their own making, and will keep happening. Their policy according to https://github.com/zsh-users/zsh-completions/blob/master/README.md is
> Completions are not accepted when already available in their available project. 

So every time a project implements its own completions, and they therefore remove theirs, it will recur.
In the case of anything-but-brew, the brew solution would be to install the corresponding formula, and assuming the formula had completions support, problem solved. Not ideal, but at least straightforward. In the case of brew, there's no `brew install brew` to make it go away.

**Comment by wadkar** [comment]
For those looking for a solution, it is mentioned in [Homebrew wiki's Tips 'n Tricks section](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Tips-N'-Tricks.md#command-tab-completion) :
```sh
ln -s "$(brew --prefix)/Library/Contributions/brew_zsh_completion.zsh" /usr/local/share/zsh/site-functions/_brew
```
This was mentioned in @UniqMartin 's [this comment](https://github.com/Homebrew/homebrew/issues/49066#issuecomment-183082585) above and I think that comment is reasonable assessment of the situation.

As far as the `$fpath` value is concerned, I believe the location `/usr/local/share/zsh/site-functions` is part of the default path. Observe:
```sh
fancy_prompt >>> zsh -f
HOSTNAME% echo $fpath
/usr/local/share/zsh/site-functions /usr/local/Cellar/zsh/5.2/share/zsh/functions
```
Finally, I think we should create the symlink in brew's `zsh-completion` formula because that seems to be the only reasonable place to create the symlink for ensuring `zsh-completion` works for `brew`.

Now, if a user doesn't `brew install zsh-completion` and uses a plugin manager (OMZ/Prezto/Zgen/Antigen/...) then she will need to visit our wiki page. If we find too many users complaining, we could request `zsh-completion` folks to point to our wiki page. This is in line with their policy of not providing completion in cases where upstream provides one. We are simply requesting that they make this policy clear to the user, and provide a link to the wiki page on how to accomplish it.

**Comment by UniqMartin** [comment]
Closing as this should no longer be an issue for most users with an up-to-date Homebrew, where the official ZSH completions are now located in `/usr/local/share/zsh/site-functions` and thus can be automatically loaded by an appropriately set-up ZSH.

**Comment by apjanke** [comment]
Just FYI:

> As far as the $fpath value is concerned, I believe the location /usr/local/share/zsh/site-functions is part of the default value for $fpath.

This depends on how `zsh` was built. A brewed `zsh` will have the Homebrew prefix locations on the path. But the system-supplied `zsh` may not. (I think the default even changed between OS X releases at some point, with `/usr/local` getting added by default.)

```
$ which zsh
/usr/local/bin/zsh
$ zsh -f -c 'echo $fpath'
/usr/local/share/zsh/site-functions /usr/local/Cellar/zsh/5.2/share/zsh/functions
$ /bin/zsh -f -c 'echo $fpath'
/usr/share/zsh/site-functions /usr/share/zsh/5.0.2/functions
```

So some config file setup may still be required to support this under the system `zsh` (which is typically the one that interactive terminal sessions will be running).
