### ISSUE TITLE
Mahout 0.11.1 has a different directory structure than expected

### ISSUE THREAD

**Issue by gandhisahil** [Homebrew/legacy-homebrew#49322]
Mahout 0.11.1 has a different directory structure than what is found when downloaded directly from website

When downloading the mahout tar file directly from mahout.apache.org the extracted folder has a bunch of extra jars and folders. Some are:
- Directories
 - conf
 - bin
 - docs
 - examples
 - h20
 - lib

Whereas the `Cellar/mahout/0.11.1/` directory has less than half of the files. I even checked the size of the extracted folder( Cellar/mahout/ = 115MB), it's 100MB less than what the original extracted folder should be(255MB).

I did some more digging, and copied the cached '/Library/Caches/Homebrew/mahout-0.11.1.tar.gz` to my desktop and extracted it. This extracted file matches with what's required (All 255MB) is extracted. 

**Fact**
HomeBrew is using the correct tar.gz file

**Issue:**
The extracted folder is very different, and doesn't contain many files. 
1. Why?
2. Is something wrong? How?
3. Is it intentional? Why?

#### brewed mahout directory structure
![brew-mahout-directory](https://cloud.githubusercontent.com/assets/6154532/13157087/f21cdf20-d6ab-11e5-9f13-46d7a342c3d5.png)
#### extracted mahout directory structure 
*(using cached '/Library/Caches/Homebrew/mahout-0.11.1.tar.gz`)*

![extracted-mahout-directory](https://cloud.githubusercontent.com/assets/6154532/13157089/f53e45ea-d6ab-11e5-9159-5060d646faa8.png)

**Comment by apjanke** [comment]
It's normal for a Homebrew formula to rearrange a Java distribution to look more like a traditional Unix program distribution, and to play well with OS X and Homebrew's sandboxing. We typically also exclude source code, build tools, and developer documentation (Homebrew mostly manages installation of applications and libraries, not source distributions). That's being done here.

In the case of Mahout, the commands in `bin/` are moved to `libexec/` so `brew` can create wrapper scripts for them (which detect `$JAVA_HOME`), and the JAR files in the distribution's root are stuffed in to `libexec` to go with the relocated commands. The developer docs in `docs/` are excluded.

There are a couple oddities here though. It's unclear to me why `lib/` is not included (and relocated to `libexec` to go with the other jars) since it contains `mahout`'s dependencies. And I don't know why `conf` is excluded. @mandrews, as the original author for the `mahout` formula, maybe you can comment here?

And `bin/` here seems to be picking up too many commands, which get linked in to the global `$(brew --prefix)/bin` directory. `mahout` is an external command, but `compute-classpath.sh` and `mahout-*.sh` look like they're for `mahout`'s internal use, and should stay in mahout's cellar. And `mahout.cmd` is a Windows script. We should tweak the formula to clean those up.

**Comment by gandhisahil** [comment]
So, what I understand, that even though the directory structure is different, it still has some libs that are missing in the final brewed mahout directory. @mandrews is there a reason why you've skipped the libs?

**Comment by apjanke** [comment]
@gandhisahil: Are you seeing any broken functionality or unexpected behavior in the installed `mahout`? If there's demonstrable breakage, we can fast-track a change to fix it.

**Comment by mandrews** [comment]
@gandhisahil @apjanke I tested current `brew install mahout` and formula is functioning. However, `brew install --HEAD mahout` is no longer functional. IIRC the directory structure was based off of similar Hadoop formulas when mahout 0.8 was the latest release. Maybe the formula could be improved to use a directory structure similar to [current Hadoop formulas](https://github.com/Homebrew/homebrew/blob/485a4f3237c1d2a218124f01d26cb37abe5d1407/Library/Formula/hadoop.rb):

- Copy `apache-mahout-distribution-0.11.1/{bin,lib,conf,examples}` to `Cellar/mahout/0.11.1/libexec/`
- Copy `apache-mahout-distribution-0.11.1/*.jar` to `Cellar/mahout/0.11.1/libexec/lib`
- Write exec script from  `Cellar/mahout/0.11.1/libexec/bin/mahout` to ` Cellar/mahout/0.11.1/bin` (omitting `mahout.cmd` and `compute-classpath.sh` et. al)

**Comment by gandhisahil** [comment]
@apjanke I'm pretty new to Mahout, so I'm not sure if something is broken.

**Comment by apjanke** [comment]
I don't know Mahout either. @mandrews' suggestion seems sensible, but I'd like to have a heavier user available to confirm it works/is the "right thing". I _think_ it's probably broken as-is due to the missing `lib/`, and should have the `conf/` available per-install, but I don't have the expertise to confirm.

Anyone actually using this `mahout` formula for heavy work?

**Comment by DomT4** [comment]
What's the status here?

**Comment by MikeMcQuaid** [comment]
If this is still broken: we'll accept PRs for this but we're not actively working on it at this time.
