### ISSUE TITLE
Error: Failure while executing: /Library/Developer/CommandLineTools/usr/bin/otool -L /usr/bin/install_name_tool

### ISSUE THREAD

**Issue by evantill** [Homebrew/legacy-homebrew#50091]
brew seems broken on OS X 10.11.3 after removing Xcode and installing CLT using `xcode-select install`

### Bug reports:

To recover some space on my HDD I removed Xcode and Reinstalled the CLT.
After that brew complains:

    Error: Failure while executing: /Library/Developer/CommandLineTools/usr/bin/otool -L /usr/bin/install_name_tool
 
In fact, `install_name_tool` is now in ` /Library/Developer/CommandLineTools/usr/bin/install_name_tool`

my `brew config` and `brew doctor` output are in the following gist : https://gist.github.com/evantill/f2ec66a037b9efb7db7b

**Comment by evantill** [comment]
trying to rerun `xcode-select --install`result in an error `xcode-select: error: command line tools are already installed, use "Software Update" to install updates`

**Comment by mikemcquaid** [comment]
I don't have Xcode installed either; you should still have a `/usr/bin/install_name_tool`.

**Comment by mikemcquaid** [comment]
Did you manually remove it?

**Comment by evantill** [comment]
I have added `brew doctor -d`to the gist https://gist.github.com/evantill/f2ec66a037b9efb7db7b

https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/diagnostic.rb#L457

**Comment by evantill** [comment]
I manually removed it following some procedure found on internet. Let me check the url if needed.

But `install_name_tool` exist not in `/usr/bin` but in `/Library/Developer/CommandLineTools/usr/bin/`

**Comment by evantill** [comment]
the url was http://osxdaily.com/2012/02/20/uninstall-xcode/ (article updated on 12/17/2015).

**Comment by evantill** [comment]
The problem seems located in [`check_for_bad_install_name_tool`](https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/diagnostic.rb#L457) which is using a hard coded path `/usr/bin/install_name_tool`.

As a counterexample see [`OS.Mac.install_name_tool`](
https://github.com/Homebrew/homebrew/blob/a072f4ca363a123cd7f72eae1949f9318c971c1d/Library/Homebrew/os/mac.rb#L60) which is using `/usr/bin/xcrun` to locate `install_name_tool`path.

Hope this help.

**Comment by evantill** [comment]
What can I do to help to solve this issue ?

**Comment by evantill** [comment]
@mikemcquaid do you consider this issue as a bug or not ?

**Comment by mikemcquaid** [comment]
@evantill I don't consider it an issue considering a system file has been removed but we'd accept a pull request to fix the hard coded versions considering there's an existing inconsistency. Could you try and open a pull request? This should help and I'm happy to walk you through anything else: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md#how-to-open-a-homebrew-pull-request-and-get-it-merged

Thanks!

**Comment by evantill** [comment]
Ok, I fixed the hardcoded version. But the `check_for_bad_install_name_tool` will check the dynamically linked libraries. It expect `/usr/lib/libxcselect.dylib`but in my system `install_name_tool`is linked to `/usr/lib/libSystem.B.dylib`

I never installed `osx-gcc-installer` nor `RailsInstaller`.

Not sure how to proceed now.

**Comment by evantill** [comment]
I checked on an other Mac (fresh install with Command Line Tools installed from the UI) and I found two install_name_tool

```
machine:~ user$ otool -L  /usr/bin/install_name_tool
/usr/bin/install_name_tool:
	/usr/lib/libxcselect.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)

machine:~ user$  otool -L  /Library/Developer/CommandLineTools/usr/bin/install_name_tool
/Library/Developer/CommandLineTools/usr/bin/install_name_tool:
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1225.1.1)
```

**Comment by mikemcquaid** [comment]
@evantill You may want to fix it so it handles your case too as it seems that there's different linkage depending on the install location.

**Comment by UniqMartin** [comment]
Just to hopefully make things clearer: The different linkage of those tools, depending on whether they are in `/usr/bin` or in `$(xcode-select -p)/usr/bin` is intentional and there's nothing wrong about that. The former are wrappers that redirect to the actual tool by asking `xcode-select` for the path where the actual tools are (and suggests to install the Command Line Tools if those haven't been set up yet). Makes sense?

**Comment by evantill** [comment]
@UniqMartin are you sure that `/usr/bin/install_name_tool` is a wrapper to the _active developer directory_ and that it should always exist or is it an assumption ?

**Comment by UniqMartin** [comment]
@evantill I was already pretty sure, but I nevertheless checked on a bare installation of OS X 10.11.3 (neither Command Line Tools nor Xcode installed). There is a [long list of binaries in `/usr/bin` that link against `/usr/lib/libxcselect.dylib`](https://gist.github.com/UniqMartin/d7b0282353f736432c1b24df42c58157), among them `install_name_tool`, `otool`, and a few other prominent ones. Almost all of them are wrappers that dispatch to the respective tool in the active developer directory (or result in a popup that suggests to install the Command Line Tools, if unavailable); if those are not wrappers, it would be very strange why almost all of them are about 18 KB in size. (I'm relatively sure it has been like that since OS X 10.9, but currently don't have a system where I can verify this quickly.)

I'm not even entirely sure how you managed to delete `/usr/bin/install_name_tool` as that should have been protected by SIP (System Integrity Protection) introduced in OS X 10.11.

**Comment by evantill** [comment]
thank you for the clarifications. SIP has been desactivated on my Mac to fix some issues with homebrew after upgrading to OS X El Capitan.

I think that we can close this issue.

**Comment by mikemcquaid** [comment]
@evantill I'd advise you re-enable it; it's a security feature and from Homebrew's perspective it stops you breaking system things we rely on.
