### ISSUE TITLE
`brew uses --recursive` is slow on Mavericks / Ruby 1.8.7

### ISSUE THREAD

**Issue by apjanke** [Homebrew/legacy-homebrew#50256]
The `brew uses --recursive` command is quite slow when run on Mavericks under Ruby 1.8.7. It's slow normally, taking a few minutes and gets very slow when run under `ruby187`.

On the test bot, the `uses --recursive` step is taking 15-20 minutes on the Mavericks box, and is the main bottleneck for test builds right now.

On my local 10.9.5 box: 3 minutes normal, 18 minutes with `ruby187`.

```
$ /usr/bin/time brew uses --recursive pyqt5
homebrew/python/matplotlib-basemap           homebrew/python/matplotlib                   homebrew/science/graph-tool
      196.02 real       185.95 user         7.80 sys
[/usr/local/Library/Homebrew on ⇄ master]
$ HOMEBREW_RUBY_PATH=/usr/local/opt/ruby187/bin/ruby /usr/bin/time brew uses --recursive pyqt5
homebrew/python/matplotlib-basemap           homebrew/python/matplotlib                   homebrew/science/graph-tool
     1115.68 real      1102.84 user        12.62 sys
[/usr/local/Library/Homebrew on ⇄ master]
$
```

On the Mavericks test bot:

<img width="733" alt="long brew uses on mavericks test bot" src="https://cloud.githubusercontent.com/assets/2618447/13897881/1a2939a8-ed97-11e5-93b7-75ba9886fc29.png">

@UniqMartin mentioned this in discussion; posting it as a bug so we can collect discussion and observations on it.

###  Some diagnosis

When I was watching this in Activity Monitor on the long runs, it kept a single core pegged at 100% utilization the whole time I saw, and racked up 15 minutes of CPU time.

On OS X 10.10, I see a similar slowdown under `ruby187`, but the absolute times aren't as bad. 1 minute normal, 8 minutes on `ruby187`.

```
$ /usr/bin/time brew uses --recursive cowsay
       82.79 real        78.39 user         2.89 sys
$ HOMEBREW_RUBY_PATH=/usr/local/opt/ruby187/bin/ruby /usr/bin/time brew uses --recursive cowsay
      445.61 real       439.32 user         5.78 sys
```

We've got about 4,500 formulae between the major taps, and each of those is a class and gets loaded by the `uses --recursive`. Could be that's just a lot of work, and the older Ruby interpreter wasn't as efficient about it.

Still, it's a lot slower on Mavericks, too.

**Comment by apjanke** [comment]
I turned on Ruby's basic profiler by adding `-rprofile` to the `ruby` invocation inside `brew.sh`. Let it under `ruby187` for about an hour before giving up (profiler overhead) but got [some results](https://gist.github.com/apjanke/e06d5130d5612b59898d).

Nothing obvious jumps out at me. Maybe 15% of the time is spent in `Pathname` operations, but that's not enough to explain the huge 1.8.7 speed difference.

**Comment by apjanke** [comment]
Actually, now that I'm looking at it: the absolute number of calls for a lot of these methods, particularly the formula construction ones, look high.

```
  %   cumulative   self              self     total
 time   seconds   seconds    calls  ms/call  ms/call  name
  1.99  1573.11     67.54    59091     1.14    23.57  Formula#initialize
  1.69  1687.92     57.35   177270     0.32     1.40  Formula#set_spec
```

50,000 calls to `Formula#initialize`? If the formula definitions are being cached, and we have around 5,000 formulae, I'd only expect to see on the order of 5,000 calls to it. That's a little surprising.

**Comment by UniqMartin** [comment]
Thanks for picking this up and coming up with some ideas! I let the profile runs finish (both with Ruby 1.8.7 and system-provided 2.0.0-p645), with the results [in this Gist](https://gist.github.com/UniqMartin/eb7e84f34f5faa621a7b). It took “only” 17.5 hours to complete, so the absolute times are not necessarily helpful, but maybe something can be concluded from the number of calls per method and a direct comparison of the profiles.

While pondering this, I also found two major performance regressions [since we started using `--recursive` on the `test-bot`](https://github.com/Homebrew/homebrew/commit/1d3b69dd54c69813d65e80f90ed4ca00de2fd3e6) (assuming `brew uses --recursive` is a meaningful benchmark). Bisecting yielded:

1. 1e864ed6b1c791250f837dd532daa66d7b4cf9e9 by me:

  - Slows down Ruby 1.8.7 by over 20%, but has no measurable impact on system Ruby.
  - I don't see an immediate solution without sacrificing the correctness fix in this commit.

2. 8acf8384579bc4f2a7762dd7d11764aee7227d6b by @xu-cheng:

  - Slows down system Ruby by factor 2, but has a much smaller impact on Ruby 1.8.7.
  - Probably easy to work around and speed up.
  - (Not meant to blame you. Just pointing this out and making you aware of the discussion in this issue, since you've already joined the discussion on this topic in the team chat.)

Those probably only surfaced because our underlying algorithms and data structures are not adequate for the task. As already discussed in the team chat, short-term some caching and long-term an overhaul of the dependency resolution code (with a graph-based representation) should improve this significantly.

**Comment by UniqMartin** [comment]
For posteriority, here are some results with a dirty hack that adds caching to `Formulary.factory`.

With Ruby 2.0.0-p645 (180% faster, nice):

```
brew uses --recursive cowsay #  92.91 real |  86.64 user |   3.96 sys | current
brew uses --recursive cowsay #  33.33 real |  30.74 user |   0.88 sys | hack
```

With Ruby 1.8.7 from `homebrew/versions` (45% faster, less impressive):

```
brew uses --recursive cowsay # 400.72 real | 379.09 user |   8.91 sys | current
brew uses --recursive cowsay # 276.90 real | 265.86 user |   5.60 sys | hack
```

The hack:

```diff
diff --git i/Library/Homebrew/formulary.rb w/Library/Homebrew/formulary.rb
index da70aed2..670ac392 100644
--- i/Library/Homebrew/formulary.rb
+++ w/Library/Homebrew/formulary.rb
@@ -204,7 +204,10 @@ class Formulary
   # * a formula URL
   # * a local bottle reference
   def self.factory(ref, spec = :stable)
-    loader_for(ref).get_formula(spec)
+    @formulae ||= Hash.new do |hash, key|
+      hash[key] = loader_for(key[0]).get_formula(key[1])
+    end
+    @formulae[[ref, spec]]
   end

   # Return a Formula instance for the given rack.
```

**Comment by apjanke** [comment]
Gonna just close this out as a known shortcoming of `brew` that we can't fix immediately, and doesn't need more discussion. We've worked around it by no longer using the `--recursive` option under `brew test-bot` so now the CI queues are running acceptably, and the upcoming switch to Ruby 2.0+ everywhere will reduce the pain further. At some point we'll have to completely rework the dependency logic, but we all know that and no reason leaving this open as a reminder.
