### ISSUE TITLE
Feature Request: Relax sandbox restrictions for formulas communicating over XPC

### ISSUE THREAD

**Issue by jpsim** [Homebrew/legacy-homebrew#50310]
As identified in #50211, Homebrew's sandbox currently restricts formulas from communicating over XPC to paths it deems it should not be allowed to write to. This makes communicating via XPC to services at paths under `/Applications` impossible in the sandbox.

In the case of #50211 it was attempting to communicate with `sourcekitd.framework` which ships with `Xcode.app`, typically installed under `/Applications/Xcode.app`.

I'm not sure if there's a way to distinguish between XPC traffic and other file system writes to disallowed locations, but if there is, it'd be nice if Homebrew's sandbox supported whitelisting which XPC services it needs to talk to.

I understand if this is too niche a feature request to implement, but until such a solution exists, the SourceKitten-dependent formulas (`sourcekitten` & `swiftlint`) won't be allowed to do anything substantial in their test to avoid creating XPC connections, just something like `sourcekitten version`.

**Comment by mikemcquaid** [comment]
CC @xu-cheng for thoughts. I suspect this is something we'd submit a pull request for but no-one will actively work on due to nicheness.

**Comment by xu-cheng** [comment]
Sorry, I simply don't have enough knowledge about OS X API to give any solution?

> Homebrew's sandbox currently restricts formulas from communicating over XPC to paths it deems it should not be allowed to write to.

I'm not sure its failure has anything to do with which path allow to write. Running test with following sandbox profile (which allows almost everything sandbox allowed and traces the operations to `/tmp/trace_output.sb`), it still failed.
```
(version 1)
(trace "/tmp/trace_output.sb")
```

```
$ sandbox-exec -f test.sb sourcekitten syntax --text 'import Foundation // Hello World'
[1]    22420 illegal hardware instruction  sandbox-exec -f test.sb sourcekitten syntax --text
```

According to [document by Apple](https://developer.apple.com/library/mac/documentation/MacOSX/Conceptual/BPSystemStartup/Chapters/CreatingXPCServices.html), XPC often is used for Privilege Separation in Sandbox. Hence, it's part of sandbox infrastructure. I can only suspect this problem is caused by Sourcekitten itself, where the way of initializing or communicating XPC service is incorrect under sandbox context.

**Comment by apjanke** [comment]
So, I read up on the XPC stuff a bit, and I don't know if this is something we can or should do. To me, it looks like XPC is used only between privilege-separated processes within a single sandboxed app, not for use by one application to communicate with another.

It's not stated front and center anywhere, but in [this other "App Sandbox Design Guide" document](https://developer.apple.com/library/mac/documentation/Security/Conceptual/AppSandboxDesignGuide/AppSandboxInDepth/AppSandboxInDepth.html#//apple_ref/doc/uid/TP40011183-CH3-SW28), it says (down near the bottom): 

> [A]n XPC service that you include with your app is accessible only by your app.

If SourceKitten is trying to use XPC to communicate with part of Xcode, this may be simply working as designed, like @xu-cheng suspects.

**Comment by apjanke** [comment]
After reading about framework installation, XPC, and OS X sandboxing some more, I don't think this is something we should do. It looks like SourceKitten is linking to a private embedded framework inside another application, which is not supported by Apple, and the sandbox is working as designed when it blocks it. I think we want to keep blocking that in sandboxed contexts.

The trade-off here is the inability to thoroughly test sandbox-violating packages vs having a mechanism to poke holes in the sandbox walls. I think we should err on the side of giving up robust testing on a few formulae, as opposed to mucking with opening the sandbox in ways probably none of us fully understand.

I'm not saying we should kick `sourcekitten` out of core Homebrew. We don't require apps to be sandbox-compliant while running. I'm saying we should declare `sourcekitten` to be okay as it is with a trivial "`--version`" test and let it keep that indefinitely, and decide we won't poke holes like this in the sandbox for the purposes of testing formulae. This isn't keeping `sourcekitten` from building or functioning fully, since we only use the sandbox in the `install` and `test` steps; once installed it does not run sandboxed.

**Comment by jpsim** [comment]
👍 sounds like a reasonable tradeoff. I'll close this. Thanks so much for looking into this!
