### ISSUE TITLE
Can brew update ignore the system git config merge.ff setting?

### ISSUE THREAD

**Issue by ferventcoder** [Homebrew/legacy-homebrew#50325]
If you have set `merge.ff=false` in your git configuration, running `brew update` stops on every merge and asks you to create the commit.

~~~ini
[merge]
	ff = false
~~~

![brew update please merge it all](https://cloud.githubusercontent.com/assets/63502/13962938/4789a04e-f031-11e5-8403-0a4a27856e80.png)

This happens for every repo, so it can get quite interesting. I know git has `--ff-only`, but that could cause issues if someone was editing files in the brew repo/formula.

Is there a way that the machine fast forward setting could be ignored? I see `update --rebase` as an option. I think I may start using that instead. I think this may still have some value though.

**Comment by ferventcoder** [comment]
`brew update --rebase` seems like a good way of running update instead if one is affected by this.

**Comment by apjanke** [comment]
I'm not sure if `brew` *can* right now, but it seems like this is something it *should* ignore. `brew` uses `git` as an implementation mechanism; it's not just a thin wrapper on top of a manually-managed Git repo, so the `brew` behavior should be largely insensitive to the user `git` configuration settings, aside from identity. IMHO, anyway.

I suspect that the current behavior is unintentional, because it wasn't tested with a global git config with `ff=false` in it. This seems to me like a bug.

**Comment by UniqMartin** [comment]
Homebrew's `brew update` has recently been modified to perform a rebase by default, thus I suspect the problem is now gone and this issue can be closed. I'm happy to reopen should I be mistaken. Thanks!

**Comment by ferventcoder** [comment]
Thanks!
